<?php

declare(strict_types=1);

/*
 * This file is part of the Valkyrja Framework package.
 *
 * (c) Melech Mizrachi <melechmizrachi@gmail.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Valkyrja\Tests\Classes\Http\Message\File;

use Override;
use Valkyrja\Http\Message\File\UploadedFile;

/**
 * Class MoveFailureExceptionClass.
 */
class MoveFailureExceptionClass extends UploadedFile
{
    /**
     * @inheritDoc
     */
    #[Override]
    protected function shouldWriteStream(): bool
    {
        return false;
    }

    /**
     * @inheritDoc
     */
    #[Override]
    protected function moveUploadedFile(string $from, string $to): bool
    {
        $result = parent::moveUploadedFile($from, $to); // TODO: Change the autogenerated stub

        // Cleanup and remove the test file created
        $this->deleteFile($from);

        return $result;
    }
}
