<?php

declare(strict_types=1);

/*
 * This file is part of the Valkyrja Framework package.
 *
 * (c) Melech Mizrachi <melechmizrachi@gmail.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Valkyrja\Tests\Unit\Container\Generator;

use Valkyrja\Container\Data\Data;
use Valkyrja\Container\Generator\DataFileGenerator;
use Valkyrja\Support\Directory\Directory;
use Valkyrja\Support\Generator\Enum\GenerateStatus;
use Valkyrja\Tests\EnvClass;
use Valkyrja\Tests\Unit\Abstract\TestCase;

final class DataFileGeneratorTest extends TestCase
{
    public function testGenerateFile(): void
    {
        Directory::$BASE_PATH = EnvClass::APP_DIR;

        $filePath  = Directory::dataPath('testGenerateFile-container.php');
        $data      = new Data();
        $generator = new DataFileGenerator($filePath, $data);
        $results   = $generator->generateFile();

        self::assertSame(GenerateStatus::SUCCESS, $results);
        self::assertSame($generator->generateFileContents(), @file_get_contents($filePath));

        @unlink($filePath);
    }

    public function testGenerateFileContents(): void
    {
        $data      = new Data();
        $generator = new DataFileGenerator('container.php', $data);
        $contents  = $generator->generateFileContents();

        $dataContents = $generator->generateClassContents();

        $expected = <<<PHP
            <?php

            declare(strict_types=1);

            // This file was automatically generated by the Valkyrja Framework.

            return $dataContents;
            PHP;

        self::assertNotEmpty($contents);
        self::assertSame($expected, $contents);
    }

    public function testGenerateClassContents(): void
    {
        $data      = new Data();
        $generator = new DataFileGenerator('container.php', $data);
        $contents  = $generator->generateClassContents();

        $dataNamespace = Data::class;

        $expected = <<<PHP
            new $dataNamespace(
                aliases: array (
            ),
                deferred: array (
            ),
                deferredCallback: array (
            ),
                services: array (
            ),
                singletons: array (
            ),
                providers: array (
            )
            )
            PHP;

        self::assertNotEmpty($contents);
        self::assertSame($expected, $contents);
    }
}
