preset: recommended

risky: true

enabled:
  - align_equals
  - blank_line_before_break
  - combine_consecutive_unsets
  - concat_with_spaces
  - const_visibility_required
  - no_useless_else
  - not_operator_with_successor_space
  - short_list_syntax
  - strict_comparison
  - strict_param
  - phpdoc_add_missing_param_annotation
  - declare_strict_types
  - dir_constant
  - final_static_access
  - blank_line_before_declare

disabled:
  - concat_without_spaces
  - phpdoc_align
  - unalign_equals
  - phpdoc_summary
  - no_blank_lines_between_imports
  - alpha_ordered_imports
  - switch_case_space
