preset: recommended

risky: true

enabled:
  - align_equals
  - combine_consecutive_unsets
  - concat_with_spaces
  - const_visibility_required
  - no_useless_else
  - not_operator_with_successor_space
  - short_list_syntax
  - strict_comparison
  - strict_param

disabled:
  - concat_without_spaces
  - unalign_equals