language: php

php:
  - 8.1

env:
  global:
    - setup=basic

matrix:
  fast_finish: true
  include:
    - php: 8.1
      env: setup=basic
    - php: 8.1
      env: setup=lowest
    - php: 8.1
      env: setup=stable

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

before_install:
  - travis_retry composer self-update

install:
  - if [[ $setup = 'basic' ]]; then travis_retry composer install --no-interaction --prefer-dist --no-suggest; fi
  - if [[ $setup = 'stable' ]]; then travis_retry composer update --prefer-dist --no-interaction --prefer-stable --no-suggest; fi
  - if [[ $setup = 'lowest' ]]; then travis_retry composer update --prefer-dist --no-interaction --prefer-lowest --prefer-stable --no-suggest; fi

script:
  - mkdir -p build/logs
  - XDEBUG_MODE=coverage vendor/bin/phpunit --coverage-text --stderr

after_success:
  - bash <(curl -s https://codecov.io/bash)
  - travis_retry php vendor/bin/php-coveralls
