<?php

declare(strict_types=1);

/*
 * This file is part of the Valkyrja Framework package.
 *
 * (c) Melech Mizrachi <melechmizrachi@gmail.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Valkyrja\Tests\Classes\Http\Message\Stream\Psr;

use Override;
use Valkyrja\Http\Message\Stream\Psr\Stream;

/**
 * Class StreamEmptyModeClass.
 */
class StreamEmptyModeClass extends Stream
{
    #[Override]
    public function getMetadata(string|null $key = null): mixed
    {
        if ($key === 'mode') {
            return null;
        }

        return parent::getMetadata($key); // TODO: Change the autogenerated stub
    }
}
