<?php

declare(strict_types=1);

/*
 * This file is part of the Valkyrja Framework package.
 *
 * (c) Melech Mizrachi <melechmizrachi@gmail.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Valkyrja\Http\Server\Generator;

use Override;
use Valkyrja\Http\Message\Header\Collection\HeaderCollection;
use Valkyrja\Http\Message\Header\Header;
use Valkyrja\Http\Message\Response\Contract\RedirectResponseContract;
use Valkyrja\Http\Message\Response\Contract\ResponseContract;
use Valkyrja\Http\Message\Uri\Factory\UriFactory;
use Valkyrja\Http\Server\Generator\Contract\ResponseFileGeneratorContract;
use Valkyrja\Support\Generator\Abstract\FileGenerator;

class ResponseFileGenerator extends FileGenerator implements ResponseFileGeneratorContract
{
    /**
     * @param non-empty-string $filePath The file path
     */
    public function __construct(
        protected ResponseContract $response,
        string $filePath
    ) {
        parent::__construct($filePath);
    }

    /**
     * @inheritDoc
     */
    #[Override]
    public function generateFileContents(): string
    {
        $response = $this->response;

        $responseClassName = $response::class;

        $streamContents = $this->getStreamContents();

        $statusCodeContents = $this->generateObjectsContents($response->getStatusCode());
        $statusPhrase       = $response->getReasonPhrase();

        $headerCollectionClassName = HeaderCollection::class;

        $headersContentsAsString = $this->getHeadersContents();

        $additionalResponseWithMethods = $this->getAdditionalResponseWithMethods();

        // withBody is used because not all responses may allow a body to be passed via the constructor
        return <<<PHP
            <?php

            declare(strict_types=1);

            // This file was automatically generated by the Valkyrja Framework.

            $streamContents

            \$response = new $responseClassName(
                headers: new $headerCollectionClassName(
                    $headersContentsAsString
                )
            )
                ->withStatus($statusCodeContents, '$statusPhrase')
                ->withBody(\$stream)
                $additionalResponseWithMethods;

            return \$response;
            PHP;
    }

    /**
     * Get any additional methods to add to the response.
     */
    protected function getAdditionalResponseWithMethods(): string
    {
        $contents = '';

        $contents .= $this->getRedirectResponseContents();

        return $contents;
    }

    /**
     * Get the redirect response contents.
     */
    protected function getRedirectResponseContents(): string
    {
        $response = $this->response;

        if ($response instanceof RedirectResponseContract) {
            $uriFactoryClassName = UriFactory::class;

            $uri = $response->getUri()->__toString();

            return <<<PHP
                ->withUri($uriFactoryClassName::fromString('$uri'))
                PHP;
        }

        return '';
    }

    /**
     * Get the stream contents.
     *
     * @return non-empty-string
     */
    protected function getStreamContents(): string
    {
        $stream         = $this->response->getBody();
        $streamContents = $stream->getContents();

        $stream->rewind();

        $streamClassContents = $this->generateObjectsContents($stream);
        $streamClassContents = $this->replaceResourceInStream($streamClassContents);

        return <<<PHP
            \$stream = $streamClassContents;

            if (\$stream->isWritable()) {
                \$stream->write(
            <<<HTML
            $streamContents
            HTML
                );
                \$stream->rewind();
            }
            PHP;
    }

    /**
     * Get the headers contents.
     */
    protected function getHeadersContents(): string
    {
        $headers = $this->response->getHeaders()->getHeaders();

        $headersContents = [];

        foreach ($headers as $header) {
            $headerClassName = Header::class;
            $headerName      = $header->getName();
            $headerContents  = $header->getValuesAsString();

            $headersContents[] = <<<PHP
                new $headerClassName(
                    '$headerName',
                    '$headerContents'
                ),
                PHP;
        }

        $headersContentsAsString = implode('', $headersContents);

        return $headersContentsAsString;
    }

    /**
     * Replace the resource in the stream.
     */
    protected function replaceResourceInStream(string $responseContents): string
    {
        return str_replace("'resource' => NULL,", '', $responseContents);
    }
}
