<?php

declare(strict_types=1);

/*
 * This file is part of the Valkyrja Framework package.
 *
 * (c) Melech Mizrachi <melechmizrachi@gmail.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Valkyrja\Tests\Unit\Event\Generator;

use Valkyrja\Application\Directory\Directory;
use Valkyrja\Dispatch\Data\MethodDispatch;
use Valkyrja\Event\Data\Data;
use Valkyrja\Event\Data\Listener;
use Valkyrja\Event\Generator\DataProviderFileGenerator;
use Valkyrja\Support\Generator\Enum\GenerateStatus;
use Valkyrja\Tests\EnvClass;
use Valkyrja\Tests\Unit\Abstract\TestCase;

final class DataProviderFileGeneratorTest extends TestCase
{
    public function testGenerateFile(): void
    {
        Directory::$basePath = EnvClass::APP_DIR;

        $directory  = Directory::storagePath();
        $className  = 'EventDataTestDataProvider';
        $filePath   = "$directory/$className.php";
        $data       = new Data();
        $generator  = new DataProviderFileGenerator(
            directory: $directory,
            data: $data,
            namespace: EnvClass::APP_DATA_NAMESPACE,
            className: $className
        );
        $results   = $generator->generateFile();

        self::assertSame(GenerateStatus::SUCCESS, $results);
        self::assertSame($generator->generateFileContents(), @file_get_contents($filePath));

        @unlink($filePath);
    }

    public function testGenerateFileContents(): void
    {
        $directory  = Directory::storagePath();
        $className  = 'EventDataTestDataProvider';
        $data       = new Data();
        $generator  = new DataProviderFileGenerator(
            directory: $directory,
            data: $data,
            namespace: EnvClass::APP_DATA_NAMESPACE,
            className: $className
        );
        $contents  = $generator->generateFileContents();

        $dataContents = $generator->generateClassContents();

        $expected = <<<PHP
            <?php

            declare(strict_types=1);

            // This file was automatically generated by the Valkyrja Framework.

            namespace App\Provider\Data;

            use Override;
            use Valkyrja\Event\Data\Data;
            use Valkyrja\Container\Provider\Provider;
            use Valkyrja\Container\Manager\Contract\ContainerContract;


            final class EventDataTestDataProvider extends Provider
            {
                /**
                 * @inheritDoc
                 */
                #[Override]
                public static function publishers(): array
                {
                    return [
                        Data::class => [self::class, 'publishData'],
                    ];
                }

                /**
                 * @inheritDoc
                 */
                #[Override]
                public static function provides(): array
                {
                    return [
                        Data::class,
                    ];
                }

                /**
                 * Publish the service.
                 */
                public static function publishData(ContainerContract \$container): void
                {
                    \$data = $dataContents;

            \$container->setSingleton(Data::class, \$data);
                }
            }

            PHP;

        self::assertNotEmpty($contents);
        self::assertSame($expected, $contents);
    }

    public function testGenerateClassContents(): void
    {
        $directory  = Directory::storagePath();
        $className  = 'EventDataTestDataProvider';
        $data       = new Data();
        $generator  = new DataProviderFileGenerator(
            directory: $directory,
            data: $data,
            namespace: EnvClass::APP_DATA_NAMESPACE,
            className: $className
        );
        $contents  = $generator->generateClassContents();

        $dataNamespace = Data::class;

        // phpcs:disable
        $expected = <<<PHP
            new \\$dataNamespace(
                events: array (
            ),
                listeners: [
                
            ],
            )
            PHP;
        // phpcs:enable

        self::assertNotEmpty($contents);
        self::assertSame($expected, $contents);
    }

    public function testGenerateClassContentsWithRoute(): void
    {
        $data      = new Data(
            listeners: [
                'name' => new Listener(
                    eventId: 'eventId',
                    name: 'name',
                    dispatch: new MethodDispatch('class', 'method')
                ),
            ]
        );
        $directory  = Directory::storagePath();
        $className  = 'EventDataTestDataProvider';
        $generator  = new DataProviderFileGenerator(
            directory: $directory,
            data: $data,
            namespace: EnvClass::APP_DATA_NAMESPACE,
            className: $className
        );
        $contents  = $generator->generateClassContents();

        $dataNamespace = Data::class;

        // phpcs:disable
        $expected = <<<PHP
            new \\$dataNamespace(
                events: array (
            ),
                listeners: [
                'name' => static fn (): \Valkyrja\Event\Data\Contract\ListenerContract => new \Valkyrja\Event\Data\Listener(...array(
               'eventId' => 'eventId',
               'name' => 'name',
               'dispatch' => 
              new \Valkyrja\Dispatch\Data\MethodDispatch(...array(
                 'class' => 'class',
                 'arguments' => 
                array (
                ),
                 'dependencies' => 
                array (
                ),
                 'method' => 'method',
                 'isStatic' => false,
              )),
            )),
            
            ],
            )
            PHP;
        // phpcs:enable

        self::assertNotEmpty($contents);
        self::assertSame($expected, $contents);
    }

    public function testGenerateClassContentsWithRouteClosure(): void
    {
        $data      = new Data(
            listeners: [
                'name' => static fn (): Listener => new Listener(
                    eventId: 'eventId',
                    name: 'name',
                    dispatch: new MethodDispatch('class', 'method')
                ),
            ]
        );
        $directory  = Directory::storagePath();
        $className  = 'EventDataTestDataProvider';
        $generator  = new DataProviderFileGenerator(
            directory: $directory,
            data: $data,
            namespace: EnvClass::APP_DATA_NAMESPACE,
            className: $className
        );
        $contents  = $generator->generateClassContents();

        $dataNamespace = Data::class;

        // phpcs:disable
        $expected = <<<PHP
            new \\$dataNamespace(
                events: array (
            ),
                listeners: [
                'name' => static fn (): \Valkyrja\Event\Data\Contract\ListenerContract => new \Valkyrja\Event\Data\Listener(...array(
               'eventId' => 'eventId',
               'name' => 'name',
               'dispatch' => 
              new \Valkyrja\Dispatch\Data\MethodDispatch(...array(
                 'class' => 'class',
                 'arguments' => 
                array (
                ),
                 'dependencies' => 
                array (
                ),
                 'method' => 'method',
                 'isStatic' => false,
              )),
            )),
            
            ],
            )
            PHP;
        // phpcs:enable

        self::assertNotEmpty($contents);
        self::assertSame($expected, $contents);
    }
}
