<?php

declare(strict_types=1);

/*
 * This file is part of the Valkyrja Framework package.
 *
 * (c) Melech Mizrachi <melechmizrachi@gmail.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Valkyrja\Tests\Unit\Event\Generator;

use Valkyrja\Application\Directory\Directory;
use Valkyrja\Event\Data\Contract\ListenerContract;
use Valkyrja\Event\Data\EventData;
use Valkyrja\Event\Data\Listener;
use Valkyrja\Event\Generator\DataFileGenerator;
use Valkyrja\Support\Generator\Enum\GenerateStatus;
use Valkyrja\Tests\Unit\Abstract\TestCase;

final class DataFileGeneratorTest extends TestCase
{
    public function testGenerateFile(): void
    {
        $directory  = Directory::storagePath();
        $className  = 'EventDataTestData';
        $filePath   = "$directory/$className.php";
        $data       = new EventData();
        $generator  = new DataFileGenerator(
            directory: $directory,
            data: $data,
            namespace: 'App',
            className: $className
        );
        $results   = $generator->generateFile();

        self::assertSame(GenerateStatus::SUCCESS, $results);
        self::assertSame($generator->generateFileContents(), @file_get_contents($filePath));

        @unlink($filePath);
    }

    public function testGenerateFileContents(): void
    {
        $directory  = Directory::storagePath();
        $className  = 'EventDataTestData';
        $namespace  = 'App';
        $data       = new EventData();
        $generator  = new DataFileGenerator(
            directory: $directory,
            data: $data,
            namespace: $namespace,
            className: $className
        );
        $contents  = $generator->generateFileContents();

        $expected = <<<PHP
            <?php

            declare(strict_types=1);

            // This file was automatically generated by the Valkyrja Framework.

            namespace $namespace;

            use Valkyrja\Event\Data\EventData;

            final readonly class $className extends EventData
            {
                public function __construct()
                {
                    parent::__construct(
                        events: array (
            ),
            listeners: [
                
            ],
                    );
                }
            }

            PHP;

        self::assertNotEmpty($contents);
        self::assertSame($expected, $contents);
    }

    public function testGenerateClassContents(): void
    {
        $directory  = Directory::storagePath();
        $className  = 'EventDataTestData';
        $data       = new EventData();
        $generator  = new DataFileGenerator(
            directory: $directory,
            data: $data,
            namespace: 'App',
            className: $className
        );
        $contents  = $generator->generateClassContents();

        $dataNamespace = EventData::class;

        // phpcs:disable
        $expected = <<<PHP
            new \\$dataNamespace(
                events: array (
            ),
            listeners: [
                
            ],
            )
            PHP;
        // phpcs:enable

        self::assertNotEmpty($contents);
        self::assertSame($expected, $contents);
    }

    public function testGenerateClassContentsWithRoute(): void
    {
        $data      = new EventData(
            listeners: [
                'name' => static fn (): ListenerContract => new Listener(
                    eventId: 'eventId',
                    name: 'name',
                    handler: static fn () => null
                ),
            ]
        );
        $directory  = Directory::storagePath();
        $className  = 'EventDataTestData';
        $generator  = new DataFileGenerator(
            directory: $directory,
            data: $data,
            namespace: 'App',
            className: $className
        );
        $contents  = $generator->generateClassContents();

        $dataNamespace = EventData::class;

        // phpcs:disable
        $expected = <<<PHP
            new \\$dataNamespace(
                events: array (
            ),
            listeners: [
                'name' => static fn (): \Valkyrja\Event\Data\Contract\ListenerContract => new \Valkyrja\Event\Data\Listener(...array(
               'handler' => 
              new \Closure(...array(
              )),
               'eventId' => 'eventId',
               'name' => 'name',
            )),
            
            ],
            )
            PHP;
        // phpcs:enable

        self::assertNotEmpty($contents);
        self::assertSame($expected, $contents);
    }

    public function testGenerateClassContentsWithRouteClosure(): void
    {
        $data      = new EventData(
            listeners: [
                'name' => static fn (): Listener => new Listener(
                    eventId: 'eventId',
                    name: 'name',
                    handler: static fn () => null
                ),
            ]
        );
        $directory  = Directory::storagePath();
        $className  = 'EventDataTestData';
        $generator  = new DataFileGenerator(
            directory: $directory,
            data: $data,
            namespace: 'App',
            className: $className
        );
        $contents  = $generator->generateClassContents();

        $dataNamespace = EventData::class;

        // phpcs:disable
        $expected = <<<PHP
            new \\$dataNamespace(
                events: array (
            ),
            listeners: [
                'name' => static fn (): \Valkyrja\Event\Data\Contract\ListenerContract => new \Valkyrja\Event\Data\Listener(...array(
               'handler' => 
              new \Closure(...array(
              )),
               'eventId' => 'eventId',
               'name' => 'name',
            )),
            
            ],
            )
            PHP;
        // phpcs:enable

        self::assertNotEmpty($contents);
        self::assertSame($expected, $contents);
    }
}
