<?php

declare(strict_types=1);

/*
 * This file is part of the Valkyrja Framework package.
 *
 * (c) Melech Mizrachi <melechmizrachi@gmail.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Valkyrja\Tests\Unit\Event\Generator;

use Valkyrja\Dispatch\Data\MethodDispatch;
use Valkyrja\Event\Data\Data;
use Valkyrja\Event\Data\Listener;
use Valkyrja\Event\Generator\DataFileGenerator;
use Valkyrja\Support\Directory\Directory;
use Valkyrja\Support\Generator\Enum\GenerateStatus;
use Valkyrja\Tests\EnvClass;
use Valkyrja\Tests\Unit\Abstract\TestCase;

final class DataFileGeneratorTest extends TestCase
{
    public function testGenerateFile(): void
    {
        Directory::$BASE_PATH = EnvClass::APP_DIR;

        $filePath  = Directory::dataPath('testGenerateFile-events.php');
        $data      = new Data();
        $generator = new DataFileGenerator($filePath, $data);
        $results   = $generator->generateFile();

        self::assertSame(GenerateStatus::SUCCESS, $results);
        self::assertSame($generator->generateFileContents(), @file_get_contents($filePath));

        @unlink($filePath);
    }

    public function testGenerateFileContents(): void
    {
        $data      = new Data();
        $generator = new DataFileGenerator('events.php', $data);
        $contents  = $generator->generateFileContents();

        $dataContents = $generator->generateClassContents();

        $expected = <<<PHP
            <?php

            declare(strict_types=1);

            // This file was automatically generated by the Valkyrja Framework.

            return $dataContents;
            PHP;

        self::assertNotEmpty($contents);
        self::assertSame($expected, $contents);
    }

    public function testGenerateClassContents(): void
    {
        $data      = new Data();
        $generator = new DataFileGenerator('events.php', $data);
        $contents  = $generator->generateClassContents();

        $dataNamespace = Data::class;

        $expected = <<<PHP
            new $dataNamespace(
                events: array (
            ),
                listeners: [
                
            ],
            )
            PHP;

        self::assertNotEmpty($contents);
        self::assertSame($expected, $contents);
    }

    public function testGenerateClassContentsWithRoute(): void
    {
        $data      = new Data(
            listeners: [
                'name' => new Listener(
                    eventId: 'eventId',
                    name: 'name',
                    dispatch: new MethodDispatch('class', 'method')
                ),
            ]
        );
        $generator = new DataFileGenerator('events.php', $data);
        $contents  = $generator->generateClassContents();

        $dataNamespace = Data::class;

        // phpcs:disable
        $expected = <<<PHP
            new $dataNamespace(
                events: array (
            ),
                listeners: [
                'name' => static fn (): Valkyrja\Event\Data\Contract\ListenerContract => new \Valkyrja\Event\Data\Listener(...array(
               'eventId' => 'eventId',
               'name' => 'name',
               'dispatch' => 
              new \Valkyrja\Dispatch\Data\MethodDispatch(...array(
                 'class' => 'class',
                 'arguments' => NULL,
                 'dependencies' => NULL,
                 'method' => 'method',
                 'isStatic' => false,
              )),
            )),
            
            ],
            )
            PHP;
        // phpcs:enable

        self::assertNotEmpty($contents);
        self::assertSame($expected, $contents);
    }

    public function testGenerateClassContentsWithRouteClosure(): void
    {
        $data      = new Data(
            listeners: [
                'name' => static fn (): Listener => new Listener(
                    eventId: 'eventId',
                    name: 'name',
                    dispatch: new MethodDispatch('class', 'method')
                ),
            ]
        );
        $generator = new DataFileGenerator('events.php', $data);
        $contents  = $generator->generateClassContents();

        $dataNamespace = Data::class;

        // phpcs:disable
        $expected = <<<PHP
            new $dataNamespace(
                events: array (
            ),
                listeners: [
                'name' => static fn (): Valkyrja\Event\Data\Contract\ListenerContract => new \Valkyrja\Event\Data\Listener(...array(
               'eventId' => 'eventId',
               'name' => 'name',
               'dispatch' => 
              new \Valkyrja\Dispatch\Data\MethodDispatch(...array(
                 'class' => 'class',
                 'arguments' => NULL,
                 'dependencies' => NULL,
                 'method' => 'method',
                 'isStatic' => false,
              )),
            )),
            
            ],
            )
            PHP;
        // phpcs:enable

        self::assertNotEmpty($contents);
        self::assertSame($expected, $contents);
    }
}
