<?php

declare(strict_types=1);

/*
 * This file is part of the Valkyrja Framework package.
 *
 * (c) Melech Mizrachi <melechmizrachi@gmail.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Valkyrja\Http\Routing\Generator;

use Override;
use Valkyrja\Http\Routing\Data\Contract\RouteContract;
use Valkyrja\Http\Routing\Data\Data;
use Valkyrja\Http\Routing\Generator\Contract\DataFileGeneratorContract;
use Valkyrja\Support\Generator\Abstract\FileGenerator;

use function is_callable;

class DataFileGenerator extends FileGenerator implements DataFileGeneratorContract
{
    /**
     * @param non-empty-string $directory The directory
     * @param non-empty-string $namespace The class namespace
     * @param non-empty-string $className The class name
     */
    public function __construct(
        protected string $directory,
        protected Data $data,
        protected string $namespace,
        protected string $className,
    ) {
        parent::__construct(filePath: rtrim($directory, '/') . "/$className.php");
    }

    /**
     * @inheritDoc
     */
    #[Override]
    public function generateFileContents(): string
    {
        $namespace = $this->namespace;
        $className = $this->className;
        $contents  = $this->generateClassNamedArguments();

        return <<<PHP
            <?php

            declare(strict_types=1);

            // This file was automatically generated by the Valkyrja Framework.

            namespace $namespace;

            use Valkyrja\Http\Routing\Data\Data as ValkyrjaData;

            final readonly class $className extends ValkyrjaData
            {
                public function __construct()
                {
                    parent::__construct(
                        $contents
                    );
                }
            }

            PHP;
    }

    /**
     * @inheritDoc
     */
    #[Override]
    public function generateClassContents(): string
    {
        $dataNamespace = Data::class;

        $contents = $this->generateClassNamedArguments();

        // phpcs:disable
        return <<<PHP
            new \\$dataNamespace(
                $contents
            )
            PHP;
        // phpcs:enable
    }

    /**
     * Generate the class named arguments.
     */
    protected function generateClassNamedArguments(): string
    {
        $data          = $this->data;

        $paths         = var_export($data->paths, true);
        $dynamicPaths  = var_export($data->dynamicPaths, true);
        $regexes       = var_export($data->regexes, true);
        $routes        = $this->getRoutesAsContent();

        // phpcs:disable
        return <<<PHP
            routes: $routes,
            paths: $paths,
            dynamicPaths: $dynamicPaths,
            regexes: $regexes
            PHP;
        // phpcs:enable
    }

    /**
     * Get all routes as a string.
     *
     * @return non-empty-string
     */
    protected function getRoutesAsContent(): string
    {
        $routes = $this->data->routes;

        $routesContent = '';

        foreach ($routes as $key => $route) {
            if (is_callable($route)) {
                $route = $route();
            }

            $routeContent = $this->getRouteAsContent($route);

            $routesContent .= <<<PHP
                '$key' => $routeContent,

                PHP;
        }

        return <<<PHP
            [
                $routesContent
            ]
            PHP;
    }

    /**
     * Get the route as a string.
     *
     * @return non-empty-string
     */
    protected function getRouteAsContent(RouteContract $route): string
    {
        $contract = RouteContract::class;
        $content  = $this->generateObjectsContents($route);

        // phpcs:disable
        return <<<PHP
            static fn (): \\$contract => $content
            PHP;
        // phpcs:enable
    }
}
