<?php

declare(strict_types=1);

/*
 * This file is part of the Valkyrja Framework package.
 *
 * (c) Melech Mizrachi <melechmizrachi@gmail.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Valkyrja\Tests\Unit\Cli\Routing\Generator;

use Valkyrja\Application\Directory\Directory;
use Valkyrja\Cli\Routing\Data\CliRoutingData;
use Valkyrja\Cli\Routing\Data\Route;
use Valkyrja\Cli\Routing\Generator\DataFileGenerator;
use Valkyrja\Support\Generator\Enum\GenerateStatus;
use Valkyrja\Tests\Classes\Cli\Routing\Command\CommandWithAllAttributesClass;
use Valkyrja\Tests\Unit\Abstract\TestCase;

final class DataFileGeneratorTest extends TestCase
{
    public function testGenerateFile(): void
    {
        $directory  = Directory::storagePath();
        $className  = 'CliDataTestRoutingData';
        $filePath   = "$directory/$className.php";
        $data       = new CliRoutingData();
        $generator  = new DataFileGenerator(
            directory: $directory,
            data: $data,
            namespace: 'App',
            className: $className
        );
        $results   = $generator->generateFile();

        self::assertSame(GenerateStatus::SUCCESS, $results);
        self::assertSame($generator->generateFileContents(), @file_get_contents($filePath));

        @unlink($filePath);
    }

    public function testGenerateFileContents(): void
    {
        $directory  = Directory::storagePath();
        $className  = 'CliDataTestRoutingData';
        $namespace  = 'App';
        $data       = new CliRoutingData();
        $generator  = new DataFileGenerator(
            directory: $directory,
            data: $data,
            namespace: $namespace,
            className: $className
        );
        $contents  = $generator->generateFileContents();

        $expected = <<<PHP
            <?php

            declare(strict_types=1);

            // This file was automatically generated by the Valkyrja Framework.

            namespace $namespace;

            use Valkyrja\Cli\Routing\Data\CliRoutingData;

            final readonly class $className extends CliRoutingData
            {
                public function __construct()
                {
                    parent::__construct(
                        routes: [
                
            ],
                    );
                }
            }

            PHP;

        self::assertNotEmpty($contents);
        self::assertSame($expected, $contents);
    }

    public function testGenerateClassContents(): void
    {
        $directory  = Directory::storagePath();
        $className  = 'CliDataTestRoutingData';
        $data       = new CliRoutingData();
        $generator  = new DataFileGenerator(
            directory: $directory,
            data: $data,
            namespace: 'App',
            className: $className
        );
        $contents  = $generator->generateClassContents();

        $dataNamespace = CliRoutingData::class;

        // phpcs:disable
        $expected = <<<PHP
            new \\$dataNamespace(
                routes: [
                
            ],
            )
            PHP;
        // phpcs:enable

        self::assertNotEmpty($contents);
        self::assertSame($expected, $contents);
    }

    public function testGenerateClassContentsWithRoute(): void
    {
        $data      = new CliRoutingData(
            routes: [
                'route' => new Route(
                    name: 'test',
                    description: 'description',
                    handler: [CommandWithAllAttributesClass::class, 'handler']
                ),
            ]
        );
        $directory  = Directory::storagePath();
        $className  = 'CliDataTestRoutingData';
        $generator  = new DataFileGenerator(
            directory: $directory,
            data: $data,
            namespace: 'App',
            className: $className
        );
        $contents  = $generator->generateClassContents();

        $dataNamespace = CliRoutingData::class;

        // phpcs:disable
        $expected = <<<PHP
            new \\$dataNamespace(
                routes: [
                'route' => static fn (): \Valkyrja\Cli\Routing\Data\Contract\RouteContract => new \Valkyrja\Cli\Routing\Data\Route(...array(
               'helpText' => NULL,
               'handler' => 
              array (
                0 => 'Valkyrja\\\\Tests\\\\Classes\\\\Cli\\\\Routing\\\\Command\\\\CommandWithAllAttributesClass',
                1 => 'handler',
              ),
               'name' => 'test',
               'description' => 'description',
               'routeMatchedMiddleware' => 
              array (
              ),
               'routeDispatchedMiddleware' => 
              array (
              ),
               'throwableCaughtMiddleware' => 
              array (
              ),
               'exitedMiddleware' => 
              array (
              ),
               'arguments' => 
              array (
              ),
               'options' => 
              array (
              ),
            )),
            
            ],
            )
            PHP;
        // phpcs:enable

        self::assertNotEmpty($contents);
        self::assertSame($expected, $contents);
    }

    public function testGenerateClassContentsWithRouteClosure(): void
    {
        $data      = new CliRoutingData(
            routes: [
                'route' => static fn (): Route => new Route(
                    name: 'test',
                    description: 'description',
                    handler: [CommandWithAllAttributesClass::class, 'handler']
                ),
            ]
        );
        $directory  = Directory::storagePath();
        $className  = 'CliDataTestRoutingData';
        $generator  = new DataFileGenerator(
            directory: $directory,
            data: $data,
            namespace: 'App',
            className: $className
        );
        $contents  = $generator->generateClassContents();

        $dataNamespace = CliRoutingData::class;

        // phpcs:disable
        $expected = <<<PHP
            new \\$dataNamespace(
                routes: [
                'route' => static fn (): \Valkyrja\Cli\Routing\Data\Contract\RouteContract => new \Valkyrja\Cli\Routing\Data\Route(...array(
               'helpText' => NULL,
               'handler' => 
              array (
                0 => 'Valkyrja\\\\Tests\\\\Classes\\\\Cli\\\\Routing\\\\Command\\\\CommandWithAllAttributesClass',
                1 => 'handler',
              ),
               'name' => 'test',
               'description' => 'description',
               'routeMatchedMiddleware' => 
              array (
              ),
               'routeDispatchedMiddleware' => 
              array (
              ),
               'throwableCaughtMiddleware' => 
              array (
              ),
               'exitedMiddleware' => 
              array (
              ),
               'arguments' => 
              array (
              ),
               'options' => 
              array (
              ),
            )),
            
            ],
            )
            PHP;
        // phpcs:enable

        self::assertNotEmpty($contents);
        self::assertSame($expected, $contents);
    }
}
