<?php

declare(strict_types=1);

/*
 * This file is part of the Valkyrja Framework package.
 *
 * (c) Melech Mizrachi <melechmizrachi@gmail.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Valkyrja\Tests\Unit\Cli\Routing\Generator;

use Valkyrja\Application\Directory\Directory;
use Valkyrja\Cli\Routing\Data\Data;
use Valkyrja\Cli\Routing\Data\Route;
use Valkyrja\Cli\Routing\Generator\DataFileGenerator;
use Valkyrja\Dispatch\Data\MethodDispatch;
use Valkyrja\Support\Generator\Enum\GenerateStatus;
use Valkyrja\Tests\EnvClass;
use Valkyrja\Tests\Unit\Abstract\TestCase;

final class DataFileGeneratorTest extends TestCase
{
    public function testGenerateFile(): void
    {
        Directory::$basePath = EnvClass::APP_DIR;

        $filePath  = Directory::dataPath('testGenerateFile-routes.php');
        $data      = new Data();
        $generator = new DataFileGenerator($filePath, $data);
        $results   = $generator->generateFile();

        self::assertSame(GenerateStatus::SUCCESS, $results);
        self::assertSame($generator->generateFileContents(), @file_get_contents($filePath));

        @unlink($filePath);
    }

    public function testGenerateFileContents(): void
    {
        $data      = new Data();
        $generator = new DataFileGenerator('routes.php', $data);
        $contents  = $generator->generateFileContents();

        $dataContents = $generator->generateClassContents();

        $expected = <<<PHP
            <?php

            declare(strict_types=1);

            // This file was automatically generated by the Valkyrja Framework.

            return $dataContents;
            PHP;

        self::assertNotEmpty($contents);
        self::assertSame($expected, $contents);
    }

    public function testGenerateClassContents(): void
    {
        $data      = new Data();
        $generator = new DataFileGenerator('routes.php', $data);
        $contents  = $generator->generateClassContents();

        $dataNamespace = Data::class;

        $expected = <<<PHP
            new $dataNamespace(
                routes: [
                
            ],
            )
            PHP;

        self::assertNotEmpty($contents);
        self::assertSame($expected, $contents);
    }

    public function testGenerateClassContentsWithRoute(): void
    {
        $data      = new Data(
            routes: [
                'route' => new Route(
                    name: 'test',
                    description: 'description',
                    dispatch: new MethodDispatch(class: 'class', method: 'method')
                ),
            ]
        );
        $generator = new DataFileGenerator('routes.php', $data);
        $contents  = $generator->generateClassContents();

        $dataNamespace = Data::class;

        // phpcs:disable
        $expected = <<<PHP
            new $dataNamespace(
                routes: [
                'route' => static fn (): Valkyrja\Cli\Routing\Data\Contract\RouteContract => new \Valkyrja\Cli\Routing\Data\Route(...array(
               'helpText' => NULL,
               'name' => 'test',
               'description' => 'description',
               'dispatch' => 
              new \Valkyrja\Dispatch\Data\MethodDispatch(...array(
                 'class' => 'class',
                 'arguments' => NULL,
                 'dependencies' => NULL,
                 'method' => 'method',
                 'isStatic' => false,
              )),
               'routeMatchedMiddleware' => 
              array (
              ),
               'routeDispatchedMiddleware' => 
              array (
              ),
               'throwableCaughtMiddleware' => 
              array (
              ),
               'exitedMiddleware' => 
              array (
              ),
               'arguments' => 
              array (
              ),
               'options' => 
              array (
              ),
            )),
            
            ],
            )
            PHP;
        // phpcs:enable

        self::assertNotEmpty($contents);
        self::assertSame($expected, $contents);
    }

    public function testGenerateClassContentsWithRouteClosure(): void
    {
        $data      = new Data(
            routes: [
                'route' => static fn (): Route => new Route(
                    name: 'test',
                    description: 'description',
                    dispatch: new MethodDispatch(class: 'class', method: 'method')
                ),
            ]
        );
        $generator = new DataFileGenerator('routes.php', $data);
        $contents  = $generator->generateClassContents();

        $dataNamespace = Data::class;

        // phpcs:disable
        $expected = <<<PHP
            new $dataNamespace(
                routes: [
                'route' => static fn (): Valkyrja\Cli\Routing\Data\Contract\RouteContract => new \Valkyrja\Cli\Routing\Data\Route(...array(
               'helpText' => NULL,
               'name' => 'test',
               'description' => 'description',
               'dispatch' => 
              new \Valkyrja\Dispatch\Data\MethodDispatch(...array(
                 'class' => 'class',
                 'arguments' => NULL,
                 'dependencies' => NULL,
                 'method' => 'method',
                 'isStatic' => false,
              )),
               'routeMatchedMiddleware' => 
              array (
              ),
               'routeDispatchedMiddleware' => 
              array (
              ),
               'throwableCaughtMiddleware' => 
              array (
              ),
               'exitedMiddleware' => 
              array (
              ),
               'arguments' => 
              array (
              ),
               'options' => 
              array (
              ),
            )),
            
            ],
            )
            PHP;
        // phpcs:enable

        self::assertNotEmpty($contents);
        self::assertSame($expected, $contents);
    }
}
