<?php

declare(strict_types=1);

/*
 * This file is part of the Valkyrja Framework package.
 *
 * (c) Melech Mizrachi <melechmizrachi@gmail.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Valkyrja\Container\Generator\Abstract;

use Override;
use Valkyrja\Container\Manager\Contract\ContainerContract;
use Valkyrja\Container\Provider\Abstract\Provider;
use Valkyrja\Support\Generator\Abstract\FileGenerator;

abstract class ProviderFileGenerator extends FileGenerator
{
    /**
     * @param non-empty-string $directory            The directory
     * @param non-empty-string $namespace            The service provider class namespace
     * @param non-empty-string $className            The service provider class name
     * @param non-empty-string $serviceClassName     The service's class name
     * @param non-empty-string $serviceFullNamespace The service's full namespace
     * @param non-empty-string $publishMethod        The service publish method
     */
    public function __construct(
        protected string $directory,
        protected string $namespace,
        protected string $className,
        protected string $serviceClassName,
        protected string $serviceFullNamespace,
        protected string $publishMethod,
    ) {
        parent::__construct(filePath: rtrim($directory, '/') . "/$className.php");
    }

    /**
     * @inheritDoc
     */
    #[Override]
    public function generateFileContents(): string
    {
        $imports              = $this->getImports();
        $contents             = $this->getPublishContents();
        $namespace            = $this->namespace;
        $className            = $this->className;
        $serviceClassName     = $this->serviceClassName;
        $serviceFullNamespace = $this->serviceFullNamespace;
        $publishMethod        = $this->publishMethod;
        $providerContract     = Provider::class;
        $containerContract    = ContainerContract::class;

        return <<<PHP
            <?php

            declare(strict_types=1);

            // This file was automatically generated by the Valkyrja Framework.

            namespace $namespace;

            use Override;
            use $serviceFullNamespace;
            use $providerContract;
            use $containerContract;
            $imports

            final class $className extends Provider
            {
                /**
                 * @inheritDoc
                 */
                #[Override]
                public static function publishers(): array
                {
                    return [
                        $serviceClassName::class => [self::class, '$publishMethod'],
                    ];
                }

                /**
                 * @inheritDoc
                 */
                #[Override]
                public static function provides(): array
                {
                    return [
                        $serviceClassName::class,
                    ];
                }

                /**
                 * Publish the service.
                 */
                public static function $publishMethod(ContainerContract \$container): void
                {
                    $contents
                }
            }

            PHP;
    }

    /**
     * Get any custom imports.
     */
    abstract protected function getImports(): string;

    /**
     * Get the publish method contents.
     */
    abstract protected function getPublishContents(): string;
}
