<?php

declare(strict_types=1);

/*
 * This file is part of the Valkyrja Framework package.
 *
 * (c) Melech Mizrachi <melechmizrachi@gmail.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Valkyrja\Tests\Unit\Http\Server\Generator;

use Valkyrja\Http\Message\Header\Collection\HeaderCollection;
use Valkyrja\Http\Message\Header\Header;
use Valkyrja\Http\Message\Response\Response;
use Valkyrja\Http\Server\Generator\ResponseFileGenerator;
use Valkyrja\Support\Directory\Directory;
use Valkyrja\Support\Generator\Enum\GenerateStatus;
use Valkyrja\Tests\EnvClass;
use Valkyrja\Tests\Unit\Abstract\TestCase;

final class ResponseFileGeneratorTest extends TestCase
{
    public function testGenerateFile(): void
    {
        Directory::$basePath = EnvClass::APP_DIR;

        $filePath  = Directory::dataPath('testGenerateFile-response.php');
        $response  = Response::create('Hello World');
        $generator = new ResponseFileGenerator($response, $filePath);
        $results   = $generator->generateFile();

        self::assertSame(GenerateStatus::SUCCESS, $results);
        self::assertSame($generator->generateFileContents(), @file_get_contents($filePath));

        @unlink($filePath);
    }

    public function testGenerateFileWithHeaders(): void
    {
        Directory::$basePath = EnvClass::APP_DIR;

        $filePath  = Directory::dataPath('testGenerateFileWithHeaders-response.php');
        $response  = Response::create(
            'Hello World',
            headers: new HeaderCollection(
                new Header('Test', 'TestValue'),
                new Header('Test2', 'TestValue2'),
            )
        );
        $generator = new ResponseFileGenerator($response, $filePath);
        $results   = $generator->generateFile();

        self::assertSame(GenerateStatus::SUCCESS, $results);
        self::assertSame($generator->generateFileContents(), @file_get_contents($filePath));

        @unlink($filePath);
    }

    public function testGenerateFileContents(): void
    {
        $response  = Response::create('Hello World');
        $generator = new ResponseFileGenerator($response, 'response.php');
        $contents  = $generator->generateFileContents();

        self::assertNotEmpty($contents);
        self::assertStringContainsString('<?php', $contents);
        self::assertStringContainsString('declare(strict_types=1);', $contents);
        self::assertStringContainsString('// This file was automatically generated by the Valkyrja Framework.', $contents);
        self::assertStringContainsString('$stream =', $contents);
        self::assertStringContainsString('$response =', $contents);
        self::assertStringContainsString('return $response;', $contents);
        self::assertStringContainsString('Hello World', $contents);
        self::assertStringContainsString("StatusCode::OK, 'OK'", $contents);
        self::assertStringContainsString(Response::class, $contents);
    }

    public function testGenerateFileContentsWithHeaders(): void
    {
        $response  = Response::create(
            'Hello World',
            headers: new HeaderCollection(
                new Header('Test', 'TestValue'),
                new Header('Test2', 'TestValue2'),
            )
        );
        $generator = new ResponseFileGenerator($response, 'response.php');
        $contents  = $generator->generateFileContents();

        self::assertNotEmpty($contents);
        self::assertStringContainsString('<?php', $contents);
        self::assertStringContainsString('declare(strict_types=1);', $contents);
        self::assertStringContainsString('// This file was automatically generated by the Valkyrja Framework.', $contents);
        self::assertStringContainsString('$stream =', $contents);
        self::assertStringContainsString('$response =', $contents);
        self::assertStringContainsString('return $response;', $contents);
        self::assertStringContainsString('Hello World', $contents);
        self::assertStringContainsString('headers', $contents);
        self::assertStringContainsString("'Test',", $contents);
        self::assertStringContainsString("'TestValue'", $contents);
        self::assertStringContainsString("'Test2',", $contents);
        self::assertStringContainsString("'TestValue2'", $contents);
        self::assertStringContainsString("StatusCode::OK, 'OK'", $contents);
        self::assertStringContainsString(Response::class, $contents);
    }

    public function testGenerateFileContentsWithEmptyBody(): void
    {
        $response  = Response::create();
        $generator = new ResponseFileGenerator($response, 'response.php');
        $contents  = $generator->generateFileContents();

        self::assertNotEmpty($contents);
        self::assertStringContainsString('<?php', $contents);
        self::assertStringContainsString('$stream =', $contents);
        self::assertStringContainsString('$response =', $contents);
    }
}
