<?php

declare(strict_types=1);

/*
 * This file is part of the Valkyrja Framework package.
 *
 * (c) Melech Mizrachi <melechmizrachi@gmail.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Valkyrja\Tests\Unit\Http\Routing\Generator;

use Valkyrja\Application\Directory\Directory;
use Valkyrja\Http\Routing\Data\Contract\RouteContract;
use Valkyrja\Http\Routing\Data\HttpRoutingData;
use Valkyrja\Http\Routing\Data\Route;
use Valkyrja\Http\Routing\Generator\DataFileGenerator;
use Valkyrja\Support\Generator\Enum\GenerateStatus;
use Valkyrja\Tests\Classes\Http\Routing\Provider\RouteProviderClass;
use Valkyrja\Tests\Unit\Abstract\TestCase;

final class DataFileGeneratorTest extends TestCase
{
    public function testGenerateFile(): void
    {
        $directory  = Directory::storagePath();
        $className  = 'HttpDataTestRoutingData';
        $filePath   = "$directory/$className.php";
        $data       = new HttpRoutingData();
        $generator  = new DataFileGenerator(
            directory: $directory,
            data: $data,
            namespace: 'App',
            className: $className
        );
        $results    = $generator->generateFile();

        self::assertSame(GenerateStatus::SUCCESS, $results);
        self::assertSame($generator->generateFileContents(), @file_get_contents($filePath));

        @unlink($filePath);
    }

    public function testGenerateFileContents(): void
    {
        $directory  = Directory::storagePath();
        $className  = 'HttpDataTestRoutingData';
        $namespace  = 'App';
        $data       = new HttpRoutingData();
        $generator  = new DataFileGenerator(
            directory: $directory,
            data: $data,
            namespace: $namespace,
            className: $className
        );
        $contents  = $generator->generateFileContents();

        $expected = <<<PHP
            <?php

            declare(strict_types=1);

            // This file was automatically generated by the Valkyrja Framework.

            namespace $namespace;

            use Valkyrja\Http\Routing\Data\HttpRoutingData;

            final readonly class $className extends HttpRoutingData
            {
                public function __construct()
                {
                    parent::__construct(
                        routes: [
                
            ],
            paths: array (
            ),
            dynamicPaths: array (
            ),
            regexes: array (
            )
                    );
                }
            }

            PHP;

        self::assertNotEmpty($contents);
        self::assertSame($expected, $contents);
    }

    public function testGenerateClassContents(): void
    {
        $directory  = Directory::storagePath();
        $className  = 'HttpDataTestRoutingData';
        $data       = new HttpRoutingData();
        $generator  = new DataFileGenerator(
            directory: $directory,
            data: $data,
            namespace: 'App',
            className: $className
        );
        $contents  = $generator->generateClassContents();

        $dataNamespace = HttpRoutingData::class;

        // phpcs:disable
        $expected = <<<PHP
            new \\$dataNamespace(
                routes: [
                
            ],
            paths: array (
            ),
            dynamicPaths: array (
            ),
            regexes: array (
            )
            )
            PHP;
        // phpcs:enable

        self::assertNotEmpty($contents);
        self::assertSame($expected, $contents);
    }

    public function testGenerateClassContentsWithRoute(): void
    {
        $data      = new HttpRoutingData(
            routes: [
                'route' => static fn (): RouteContract => new Route(
                    '/',
                    'route',
                    [RouteProviderClass::class, 'handler']
                ),
            ]
        );
        $directory  = Directory::storagePath();
        $className  = 'HttpDataTestRoutingData';
        $generator  = new DataFileGenerator(
            directory: $directory,
            data: $data,
            namespace: 'App',
            className: $className
        );
        $contents  = $generator->generateClassContents();

        $dataNamespace = HttpRoutingData::class;

        // phpcs:disable
        $expected = <<<PHP
            new \\$dataNamespace(
                routes: [
                'route' => static fn (): \Valkyrja\Http\Routing\Data\Contract\RouteContract => new \Valkyrja\Http\Routing\Data\Route(...array(

               'handler' => 
              array (
                0 => 'Valkyrja\\\\Tests\\\\Classes\\\\Http\\\\Routing\\\\Provider\\\\RouteProviderClass',
                1 => 'handler',
              ),
               'path' => '/',
               'name' => 'route',
               'requestMethods' => 
              array (
                0 => 
                \Valkyrja\Http\Message\Enum\RequestMethod::HEAD,
                1 => 
                \Valkyrja\Http\Message\Enum\RequestMethod::GET,
              ),
               'routeMatchedMiddleware' => 
              array (
              ),
               'routeDispatchedMiddleware' => 
              array (
              ),
               'throwableCaughtMiddleware' => 
              array (
              ),
               'sendingResponseMiddleware' => 
              array (
              ),
               'terminatedMiddleware' => 
              array (
              ),
               'requestStruct' => NULL,
               'responseStruct' => NULL,
            )),
            
            ],
            paths: array (
            ),
            dynamicPaths: array (
            ),
            regexes: array (
            )
            )
            PHP;
        // phpcs:enable

        self::assertNotEmpty($contents);
        self::assertSame($expected, $contents);
    }

    public function testGenerateClassContentsWithRouteClosure(): void
    {
        $data      = new HttpRoutingData(
            routes: [
                'route' => static fn (): Route => new Route('/', 'route', [RouteProviderClass::class, 'handler']),
            ]
        );
        $directory  = Directory::storagePath();
        $className  = 'HttpDataTestRoutingData';
        $generator  = new DataFileGenerator(
            directory: $directory,
            data: $data,
            namespace: 'App',
            className: $className
        );
        $contents  = $generator->generateClassContents();

        $dataNamespace = HttpRoutingData::class;

        // phpcs:disable
        $expected = <<<PHP
            new \\$dataNamespace(
                routes: [
                'route' => static fn (): \Valkyrja\Http\Routing\Data\Contract\RouteContract => new \Valkyrja\Http\Routing\Data\Route(...array(

               'handler' => 
              array (
                0 => 'Valkyrja\\\\Tests\\\\Classes\\\\Http\\\\Routing\\\\Provider\\\\RouteProviderClass',
                1 => 'handler',
              ),
               'path' => '/',
               'name' => 'route',
               'requestMethods' => 
              array (
                0 => 
                \Valkyrja\Http\Message\Enum\RequestMethod::HEAD,
                1 => 
                \Valkyrja\Http\Message\Enum\RequestMethod::GET,
              ),
               'routeMatchedMiddleware' => 
              array (
              ),
               'routeDispatchedMiddleware' => 
              array (
              ),
               'throwableCaughtMiddleware' => 
              array (
              ),
               'sendingResponseMiddleware' => 
              array (
              ),
               'terminatedMiddleware' => 
              array (
              ),
               'requestStruct' => NULL,
               'responseStruct' => NULL,
            )),
            
            ],
            paths: array (
            ),
            dynamicPaths: array (
            ),
            regexes: array (
            )
            )
            PHP;
        // phpcs:enable

        self::assertNotEmpty($contents);
        self::assertSame($expected, $contents);
    }
}
