<?php

declare(strict_types=1);

/*
 * This file is part of the Valkyrja Framework package.
 *
 * Copyright (c) 2016-present Melech Mizrachi
 *
 * Released under the MIT License. See LICENSE.md for details.
 */

namespace Valkyrja\Tests\Fixtures\Http\Message\Stream\Psr;

use Override;
use Valkyrja\Http\Message\Stream\Psr\Stream;

/**
 * Class StreamEmptyModeFixture.
 */
final class StreamEmptyModeFixture extends Stream
{
    #[Override]
    public function getMetadata(string|null $key = null): mixed
    {
        if ($key === 'mode') {
            return null;
        }

        return parent::getMetadata($key); // TODO: Change the autogenerated stub
    }
}
