<?php

declare(strict_types=1);

/*
 * This file is part of the Valkyrja Framework package.
 *
 * (c) Melech Mizrachi <melechmizrachi@gmail.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Valkyrja\Event\Generator;

use Override;
use Valkyrja\Event\Data\Contract\ListenerContract;
use Valkyrja\Event\Data\Data;
use Valkyrja\Event\Generator\Contract\DataFileGeneratorContract;
use Valkyrja\Support\Generator\Abstract\FileGenerator;

use function is_callable;

class DataFileGenerator extends FileGenerator implements DataFileGeneratorContract
{
    /**
     * @param non-empty-string $directory The directory
     * @param non-empty-string $namespace The class namespace
     * @param non-empty-string $className The class name
     */
    public function __construct(
        protected string $directory,
        protected Data $data,
        protected string $namespace,
        protected string $className,
    ) {
        parent::__construct(filePath: rtrim($directory, '/') . "/$className.php");
    }

    /**
     * @inheritDoc
     */
    #[Override]
    public function generateFileContents(): string
    {
        $namespace = $this->namespace;
        $className = $this->className;
        $contents  = $this->generateClassNamedArguments();

        return <<<PHP
            <?php

            declare(strict_types=1);

            // This file was automatically generated by the Valkyrja Framework.

            namespace $namespace;

            use Valkyrja\Event\Data\Data as ValkyrjaData;

            final readonly class $className extends ValkyrjaData
            {
                public function __construct()
                {
                    parent::__construct(
                        $contents
                    );
                }
            }

            PHP;
    }

    /**
     * @inheritDoc
     */
    #[Override]
    public function generateClassContents(): string
    {
        $dataNamespace = Data::class;

        $contents = $this->generateClassNamedArguments();

        // phpcs:disable
        return <<<PHP
            new \\$dataNamespace(
                $contents
            )
            PHP;
        // phpcs:enable
    }

    /**
     * Generate the class named arguments.
     */
    protected function generateClassNamedArguments(): string
    {
        $events    = var_export($this->data->events, true);
        $listeners = $this->getListenersAsContent();

        // phpcs:disable
        return <<<PHP
            events: $events,
            listeners: $listeners,
            PHP;
        // phpcs:enable
    }

    /**
     * Get all listeners as a string.
     *
     * @return non-empty-string
     */
    protected function getListenersAsContent(): string
    {
        $listeners = $this->data->listeners;

        $listenersContent = '';

        foreach ($listeners as $key => $listener) {
            if (is_callable($listener)) {
                $listener = $listener();
            }

            $listenerContent = $this->getListenerAsContent($listener);

            $listenersContent .= <<<PHP
                '$key' => $listenerContent,

                PHP;
        }

        return <<<PHP
            [
                $listenersContent
            ]
            PHP;
    }

    /**
     * Get the listener as a string.
     *
     * @return non-empty-string
     */
    protected function getListenerAsContent(ListenerContract $listener): string
    {
        $contract = ListenerContract::class;
        $content  = $this->generateObjectsContents($listener);

        // phpcs:disable
        return <<<PHP
            static fn (): \\$contract => $content
            PHP;
        // phpcs:enable
    }
}
