<?php

declare(strict_types=1);

/*
 * This file is part of the Valkyrja Framework package.
 *
 * (c) Melech Mizrachi <melechmizrachi@gmail.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Valkyrja\Event\Generator;

use Override;
use Valkyrja\Application\Kernel\Contract\ApplicationContract;
use Valkyrja\Container\Manager\Contract\ContainerContract;
use Valkyrja\Container\Provider\Provider;
use Valkyrja\Event\Data\Contract\ListenerContract;
use Valkyrja\Event\Data\Data;
use Valkyrja\Event\Generator\Contract\DataFileGeneratorContract;
use Valkyrja\Event\Provider\ServiceProvider;
use Valkyrja\Support\Generator\Abstract\FileGenerator;

use function is_callable;

class DataFileGenerator extends FileGenerator implements DataFileGeneratorContract
{
    /**
     * @param non-empty-string $directory The directory
     * @param non-empty-string $namespace The class namespace
     * @param non-empty-string $className The class name
     */
    public function __construct(
        protected string $directory,
        protected Data $data,
        protected string $namespace,
        protected string $className,
    ) {
        parent::__construct(directory: rtrim($directory, '/') . "/$className.php");
    }

    /**
     * @inheritDoc
     */
    #[Override]
    public function generateFileContents(): string
    {
        $dataContents      = $this->generateClassContents();
        $bypassLogic       = $this->getDataBypassLogic();
        $namespace         = $this->namespace;
        $className         = $this->className;
        $providerContract  = Provider::class;
        $dataNamespace     = Data::class;
        $containerContract = ContainerContract::class;

        return <<<PHP
            <?php

            declare(strict_types=1);

            // This file was automatically generated by the Valkyrja Framework.

            namespace $namespace;

            use Override;
            use $dataNamespace;
            use $providerContract;
            use $containerContract;

            final class $className extends Provider
            {
                /**
                 * @inheritDoc
                 */
                #[Override]
                public static function publishers(): array
                {
                    return [
                        Data::class => [self::class, 'publishData'],
                    ];
                }

                /**
                 * @inheritDoc
                 */
                #[Override]
                public static function provides(): array
                {
                    return [
                        Data::class,
                    ];
                }

                /**
                 * Publish the data.
                 */
                public static function publishData(ContainerContract \$container): void
                {
                    $bypassLogic

                    \$data = $dataContents;

                    \$container->setSingleton(Data::class, \$data);
                }
            }

            PHP;
    }

    /**
     * @inheritDoc
     */
    #[Override]
    public function generateClassContents(): string
    {
        $dataNamespace = Data::class;

        $events    = var_export($this->data->events, true);
        $listeners = $this->getListenersAsContent();

        // phpcs:disable
        return <<<PHP
            new \\$dataNamespace(
                events: $events,
                listeners: $listeners,
            )
            PHP;
        // phpcs:enable
    }

    /**
     * Bypass logic for the data.
     */
    protected function getDataBypassLogic(): string
    {
        $applicationContract = ApplicationContract::class;
        $serviceProvider     = ServiceProvider::class;

        // phpcs:disable
        return <<<PHP
            \$app = \$container->getSingleton(\\$applicationContract::class);

            if (\$app->getDebugMode()) {
                \\$serviceProvider::publishData(\$container);

                return;
            }
            PHP;
        // phpcs:enable
    }

    /**
     * Get all listeners as a string.
     *
     * @return non-empty-string
     */
    protected function getListenersAsContent(): string
    {
        $listeners = $this->data->listeners;

        $listenersContent = '';

        foreach ($listeners as $key => $listener) {
            if (is_callable($listener)) {
                $listener = $listener();
            }

            $listenerContent = $this->getListenerAsContent($listener);

            $listenersContent .= <<<PHP
                '$key' => $listenerContent,

                PHP;
        }

        return <<<PHP
            [
                $listenersContent
            ]
            PHP;
    }

    /**
     * Get the listener as a string.
     *
     * @return non-empty-string
     */
    protected function getListenerAsContent(ListenerContract $listener): string
    {
        $contract = ListenerContract::class;
        $content  = $this->generateObjectsContents($listener);

        // phpcs:disable
        return <<<PHP
            static fn (): \\$contract => $content
            PHP;
        // phpcs:enable
    }
}
