<?php

declare(strict_types=1);

/*
 * This file is part of the Valkyrja Framework package.
 *
 * (c) Melech Mizrachi <melechmizrachi@gmail.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Valkyrja\Event\Generator;

use Override;
use Valkyrja\Event\Data\Contract\ListenerContract;
use Valkyrja\Event\Data\Data;
use Valkyrja\Event\Generator\Contract\DataFileGeneratorContract;
use Valkyrja\Support\Generator\Abstract\FileGenerator;

use function is_callable;

class DataFileGenerator extends FileGenerator implements DataFileGeneratorContract
{
    /**
     * @param non-empty-string $filePath The file path
     */
    public function __construct(
        protected string $filePath,
        protected Data $data
    ) {
        parent::__construct(filePath: $filePath);
    }

    /**
     * @inheritDoc
     */
    #[Override]
    public function generateFileContents(): string
    {
        $dataContents = $this->generateClassContents();

        return <<<PHP
            <?php

            declare(strict_types=1);

            // This file was automatically generated by the Valkyrja Framework.

            return $dataContents;
            PHP;
    }

    /**
     * @inheritDoc
     */
    #[Override]
    public function generateClassContents(): string
    {
        $dataNamespace = Data::class;

        $events    = var_export($this->data->events, true);
        $listeners = $this->getListenersAsContent();

        return <<<PHP
            new $dataNamespace(
                events: $events,
                listeners: $listeners,
            )
            PHP;
    }

    protected function getListenersAsContent(): string
    {
        $listeners = $this->data->listeners;

        $listenersContent = '';

        foreach ($listeners as $key => $route) {
            if (is_callable($route)) {
                $route = $route();
            }

            $listenerContent = $this->getListenerAsContent($route);

            $listenersContent .= <<<PHP
                '$key' => $listenerContent,

                PHP;
        }

        return <<<PHP
            [
                $listenersContent
            ]
            PHP;
    }

    protected function getListenerAsContent(ListenerContract $route): string
    {
        $contract = ListenerContract::class;
        $content  = var_export($route, true);

        return <<<PHP
            static fn (): $contract => $content
            PHP;
    }
}
