<?php

declare(strict_types=1);

/*
 * This file is part of the Valkyrja Framework package.
 *
 * (c) Melech Mizrachi <melechmizrachi@gmail.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Valkyrja\Container\Generator;

use Override;
use Valkyrja\Container\Data\Data;
use Valkyrja\Container\Generator\Contract\DataFileGeneratorContract;
use Valkyrja\Support\Generator\Abstract\FileGenerator;

class DataFileGenerator extends FileGenerator implements DataFileGeneratorContract
{
    /**
     * @param non-empty-string $filePath The file path
     */
    public function __construct(
        protected string $filePath,
        protected Data $data
    ) {
        parent::__construct(filePath: $filePath);
    }

    /**
     * @inheritDoc
     */
    #[Override]
    public function generateFileContents(): string
    {
        $dataContents = $this->generateClassContents();

        return <<<PHP
            <?php

            declare(strict_types=1);

            // This file was automatically generated by the Valkyrja Framework.

            return $dataContents;
            PHP;
    }

    /**
     * @inheritDoc
     */
    #[Override]
    public function generateClassContents(): string
    {
        $data          = $this->data;
        $dataNamespace = Data::class;

        $aliases          = var_export($data->aliases, true);
        $deferred         = var_export($data->deferred, true);
        $deferredCallback = var_export($data->deferredCallback, true);
        $services         = var_export($data->services, true);
        $singletons       = var_export($data->singletons, true);
        $providers        = var_export($data->providers, true);

        return <<<PHP
            new $dataNamespace(
                aliases: $aliases,
                deferred: $deferred,
                deferredCallback: $deferredCallback,
                services: $services,
                singletons: $singletons,
                providers: $providers
            )
            PHP;
    }
}
