<?php

declare(strict_types=1);

/*
 * This file is part of the Valkyrja Framework package.
 *
 * (c) Melech Mizrachi <melechmizrachi@gmail.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Valkyrja\Container\Generator;

use Override;
use Valkyrja\Application\Kernel\Contract\ApplicationContract;
use Valkyrja\Container\Data\Data;
use Valkyrja\Container\Generator\Contract\DataFileGeneratorContract;
use Valkyrja\Container\Manager\Contract\ContainerContract;
use Valkyrja\Container\Provider\Provider;
use Valkyrja\Container\Provider\ServiceProvider;
use Valkyrja\Support\Generator\Abstract\FileGenerator;

class DataFileGenerator extends FileGenerator implements DataFileGeneratorContract
{
    /**
     * @param non-empty-string $directory The directory
     * @param non-empty-string $namespace The class namespace
     * @param non-empty-string $className The class name
     */
    public function __construct(
        protected string $directory,
        protected Data $data,
        protected string $namespace,
        protected string $className,
    ) {
        parent::__construct(directory: rtrim($directory, '/') . "/$className.php");
    }

    /**
     * @inheritDoc
     */
    #[Override]
    public function generateFileContents(): string
    {
        $dataContents      = $this->generateClassContents();
        $bypassLogic       = $this->getDataBypassLogic();
        $namespace         = $this->namespace;
        $className         = $this->className;
        $dataNamespace     = Data::class;
        $providerContract  = Provider::class;
        $containerContract = ContainerContract::class;

        return <<<PHP
            <?php

            declare(strict_types=1);

            // This file was automatically generated by the Valkyrja Framework.

            namespace $namespace;

            use Override;
            use $dataNamespace;
            use $providerContract;
            use $containerContract;

            final class $className extends Provider
            {
                /**
                 * @inheritDoc
                 */
                #[Override]
                public static function publishers(): array
                {
                    return [
                        Data::class => [self::class, 'publishData'],
                    ];
                }

                /**
                 * @inheritDoc
                 */
                #[Override]
                public static function provides(): array
                {
                    return [
                        Data::class,
                    ];
                }

                /**
                 * Publish the data.
                 */
                public static function publishData(ContainerContract \$container): void
                {
                    $bypassLogic

                    \$data = $dataContents;

                    \$container->setSingleton(Data::class, \$data);
                }
            }

            PHP;
    }

    /**
     * @inheritDoc
     */
    #[Override]
    public function generateClassContents(): string
    {
        $data          = $this->data;
        $dataNamespace = Data::class;

        $aliases          = var_export($data->aliases, true);
        $deferred         = var_export($data->deferred, true);
        $deferredCallback = var_export($data->deferredCallback, true);
        $services         = var_export($data->services, true);
        $singletons       = var_export($data->singletons, true);
        $providers        = var_export($data->providers, true);

        // phpcs:disable
        return <<<PHP
            new \\$dataNamespace(
                aliases: $aliases,
                deferred: $deferred,
                deferredCallback: $deferredCallback,
                services: $services,
                singletons: $singletons,
                providers: $providers
            )
            PHP;
        // phpcs:enable
    }

    /**
     * Bypass logic for the data.
     */
    protected function getDataBypassLogic(): string
    {
        $applicationContract = ApplicationContract::class;
        $serviceProvider     = ServiceProvider::class;

        // phpcs:disable
        return <<<PHP
            \$app = \$container->getSingleton(\\$applicationContract::class);

            if (\$app->getDebugMode()) {
                \\$serviceProvider::publishData(\$container);

                return;
            }
            PHP;
        // phpcs:enable
    }
}
