<?php

declare(strict_types=1);

/*
 * This file is part of the Valkyrja Framework package.
 *
 * (c) Melech Mizrachi <melechmizrachi@gmail.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Valkyrja\Container\Generator;

use Override;
use Valkyrja\Container\Data\Data;
use Valkyrja\Container\Generator\Contract\DataFileGeneratorContract;
use Valkyrja\Support\Generator\Abstract\FileGenerator;

class DataFileGenerator extends FileGenerator implements DataFileGeneratorContract
{
    /**
     * @param non-empty-string $directory The directory
     * @param non-empty-string $namespace The class namespace
     * @param non-empty-string $className The class name
     */
    public function __construct(
        protected string $directory,
        protected Data $data,
        protected string $namespace,
        protected string $className,
    ) {
        parent::__construct(filePath: rtrim($directory, '/') . "/$className.php");
    }

    /**
     * @inheritDoc
     */
    #[Override]
    public function generateFileContents(): string
    {
        $namespace = $this->namespace;
        $className = $this->className;
        $contents  = $this->generateClassNamedArguments();

        return <<<PHP
            <?php

            declare(strict_types=1);

            // This file was automatically generated by the Valkyrja Framework.

            namespace $namespace;

            use Valkyrja\Container\Data\Data as ValkyrjaData;

            final readonly class $className extends ValkyrjaData
            {
                public function __construct()
                {
                    parent::__construct(
                        $contents
                    );
                }
            }

            PHP;
    }

    /**
     * @inheritDoc
     */
    #[Override]
    public function generateClassContents(): string
    {
        $dataNamespace = Data::class;

        $contents = $this->generateClassNamedArguments();

        // phpcs:disable
        return <<<PHP
            new \\$dataNamespace(
                $contents
            )
            PHP;
        // phpcs:enable
    }

    /**
     * Generate the class named arguments.
     */
    protected function generateClassNamedArguments(): string
    {
        $data = $this->data;

        $aliases          = var_export($data->aliases, true);
        $deferred         = var_export($data->deferred, true);
        $deferredCallback = var_export($data->deferredCallback, true);
        $services         = var_export($data->services, true);
        $singletons       = var_export($data->singletons, true);
        $providers        = var_export($data->providers, true);

        // phpcs:disable
        return <<<PHP
            aliases: $aliases,
            deferred: $deferred,
            deferredCallback: $deferredCallback,
            services: $services,
            singletons: $singletons,
            providers: $providers
            PHP;
        // phpcs:enable
    }
}
