<?php

declare(strict_types=1);

/*
 * This file is part of the Valkyrja Framework package.
 *
 * (c) Melech Mizrachi <melechmizrachi@gmail.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Valkyrja\Tests\Unit\Http\Server\Generator;

use Valkyrja\Http\Message\Response\Response;
use Valkyrja\Http\Server\Generator\ResponseFileGenerator;
use Valkyrja\Support\Directory\Directory;
use Valkyrja\Support\Generator\Enum\GenerateStatus;
use Valkyrja\Tests\EnvClass;
use Valkyrja\Tests\Unit\Abstract\TestCase;

class ResponseFileGeneratorTest extends TestCase
{
    public function testGenerateFile(): void
    {
        Directory::$BASE_PATH = EnvClass::APP_DIR;

        $filePath  = Directory::cachePath('testGenerateFile-response.php');
        $response  = Response::create('Hello World');
        $generator = new ResponseFileGenerator($response, $filePath);
        $results   = $generator->generateFile();

        self::assertSame(GenerateStatus::SUCCESS, $results);
        self::assertSame($generator->generateFileContents(), @file_get_contents($filePath));

        @unlink($filePath);
    }

    public function testGenerateFileContents(): void
    {
        $response  = Response::create('Hello World');
        $generator = new ResponseFileGenerator($response, 'response.php');
        $contents  = $generator->generateFileContents();

        self::assertNotEmpty($contents);
        self::assertStringContainsString('<?php', $contents);
        self::assertStringContainsString('declare(strict_types=1);', $contents);
        self::assertStringContainsString('// This file was automatically generated by the Valkyrja Framework.', $contents);
        self::assertStringContainsString('$stream =', $contents);
        self::assertStringContainsString('$response =', $contents);
        self::assertStringContainsString('return $response;', $contents);
        self::assertStringContainsString('Hello World', $contents);
        self::assertStringContainsString(Response::class, $contents);
    }

    public function testGenerateFileContentsWithEmptyBody(): void
    {
        $response  = Response::create();
        $generator = new ResponseFileGenerator($response, 'response.php');
        $contents  = $generator->generateFileContents();

        self::assertNotEmpty($contents);
        self::assertStringContainsString('<?php', $contents);
        self::assertStringContainsString('$stream =', $contents);
        self::assertStringContainsString('$response =', $contents);
    }
}
