<?php

declare(strict_types=1);

/*
 * This file is part of the Valkyrja Framework package.
 *
 * (c) Melech Mizrachi <melechmizrachi@gmail.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Valkyrja\Cli\Routing\Generator;

use Override;
use Valkyrja\Cli\Routing\Data\CliRoutingData;
use Valkyrja\Cli\Routing\Data\Contract\RouteContract;
use Valkyrja\Cli\Routing\Generator\Contract\DataFileGeneratorContract;
use Valkyrja\Support\Generator\Abstract\FileGenerator;

class DataFileGenerator extends FileGenerator implements DataFileGeneratorContract
{
    /**
     * @param non-empty-string $directory The directory
     * @param non-empty-string $namespace The class namespace
     * @param non-empty-string $className The class name
     */
    public function __construct(
        protected string $directory,
        protected CliRoutingData $data,
        protected string $namespace,
        protected string $className,
    ) {
        parent::__construct(filePath: rtrim($directory, '/') . "/$className.php");
    }

    /**
     * @inheritDoc
     */
    #[Override]
    public function generateFileContents(): string
    {
        $namespace            = $this->namespace;
        $className            = $this->className;
        $routes               = $this->getRoutesAsContent();

        return <<<PHP
            <?php

            declare(strict_types=1);

            // This file was automatically generated by the Valkyrja Framework.

            namespace $namespace;

            use Valkyrja\Cli\Routing\Data\CliRoutingData;

            final readonly class $className extends CliRoutingData
            {
                public function __construct()
                {
                    parent::__construct(
                        routes: $routes,
                    );
                }
            }

            PHP;
    }

    /**
     * @inheritDoc
     */
    #[Override]
    public function generateClassContents(): string
    {
        $dataNamespace = CliRoutingData::class;

        $routes = $this->getRoutesAsContent();

        // phpcs:disable
        return <<<PHP
            new \\$dataNamespace(
                routes: $routes,
            )
            PHP;
        // phpcs:enable
    }

    /**
     * Get all routes as a string.
     *
     * @return non-empty-string
     */
    protected function getRoutesAsContent(): string
    {
        $routes = $this->data->routes;

        $routesContent = '';

        foreach ($routes as $key => $route) {
            $route = $route();

            $routeContent = $this->getRouteAsContent($route);

            $routesContent .= <<<PHP
                '$key' => $routeContent,

                PHP;
        }

        return <<<PHP
            [
                $routesContent
            ]
            PHP;
    }

    /**
     * Get the route as a string.
     *
     * @return non-empty-string
     */
    protected function getRouteAsContent(RouteContract $route): string
    {
        $contract = RouteContract::class;
        $content  = $this->generateObjectsContents($route);

        // phpcs:disable
        return <<<PHP
            static fn (): \\$contract => $content
            PHP;
        // phpcs:enable
    }
}
