<?php

declare(strict_types=1);

/*
 * This file is part of the Valkyrja Framework package.
 *
 * (c) Melech Mizrachi <melechmizrachi@gmail.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Valkyrja\Cli\Routing\Generator;

use Override;
use Valkyrja\Cli\Routing\Data\Contract\RouteContract;
use Valkyrja\Cli\Routing\Data\Data;
use Valkyrja\Http\Routing\Generator\Contract\DataFileGeneratorContract;
use Valkyrja\Support\Generator\Abstract\FileGenerator;

use function is_callable;

class DataFileGenerator extends FileGenerator implements DataFileGeneratorContract
{
    /**
     * @param non-empty-string $filePath The file path
     */
    public function __construct(
        protected string $filePath,
        protected Data $data
    ) {
        parent::__construct(filePath: $filePath);
    }

    /**
     * @inheritDoc
     */
    #[Override]
    public function generateFileContents(): string
    {
        $dataContents = $this->generateClassContents();

        return <<<PHP
            <?php

            declare(strict_types=1);

            // This file was automatically generated by the Valkyrja Framework.

            return $dataContents;
            PHP;
    }

    /**
     * @inheritDoc
     */
    #[Override]
    public function generateClassContents(): string
    {
        $dataNamespace = Data::class;

        $routes  = $this->getRoutesAsContent();

        return <<<PHP
            new $dataNamespace(
                routes: $routes,
            )
            PHP;
    }

    protected function getRoutesAsContent(): string
    {
        $routes = $this->data->routes;

        $routesContent = '';

        foreach ($routes as $key => $route) {
            if (is_callable($route)) {
                $route = $route();
            }

            $routeContent = $this->getRouteAsContent($route);

            $routesContent .= <<<PHP
                '$key' => $routeContent,

                PHP;
        }

        return <<<PHP
            [
                $routesContent
            ]
            PHP;
    }

    protected function getRouteAsContent(RouteContract $route): string
    {
        $routeContract = RouteContract::class;
        $routeContent  = var_export($route, true);

        return <<<PHP
            static fn (): $routeContract => $routeContent
            PHP;
    }
}
