<?php

declare(strict_types=1);

/*
 * This file is part of the Valkyrja Framework package.
 *
 * Copyright (c) 2016-present Melech Mizrachi
 *
 * Released under the MIT License. See LICENSE.md for details.
 */

namespace Valkyrja\Tests\Fixtures\Http\Message\File;

use Override;
use Valkyrja\Http\Message\File\UploadedFile;

/**
 * Class MoveFailureExceptionFixture.
 */
final class MoveFailureExceptionFixture extends UploadedFile
{
    /**
     * @inheritDoc
     */
    #[Override]
    protected function shouldWriteStream(): bool
    {
        return false;
    }

    /**
     * @inheritDoc
     */
    #[Override]
    protected function moveUploadedFile(string $from, string $to): bool
    {
        $result = parent::moveUploadedFile($from, $to); // TODO: Change the autogenerated stub

        // Cleanup and remove the test file created
        $this->deleteFile($from);

        return $result;
    }
}
