name: Cherry-pick pull-requests to Branches

on:
  workflow_dispatch:
    inputs:
      destination:
        description: 'Destination branch to cherry-pick to'
        required: true
        type: string
      hash:
        description: 'Hash to cherry-pick'
        required: true

run-name: Cherry Pick ${{ inputs.hash }} To ${{ inputs.destination }}

jobs:
  cherry-pick:
    name: Cherry-pick
    uses: valkyrjaio/.github/.github/workflows/_cherry-pick-commits.yml@716065aae4466b95f0f80c9c5a5e2a92de620af6
    permissions:
      contents: write
    with:
      destination: ${{ inputs.destination }}
      hash: ${{ inputs.hash }}
      valid-branch-pattern: '^2([6-9]).x$'
