name: CI

on:
  push:
    branches: [ 'master', '*.x' ]
  pull_request:
    branches: [ 'master', '*.x' ]

permissions:
  pull-requests: write
  contents: read

jobs:
  commit-message-check:
    name: Commit Message Check
    if: github.event_name == 'pull_request'
    uses: valkyrjaio/.github/.github/workflows/_commit-message-check.yml@716065aae4466b95f0f80c9c5a5e2a92de620af6
    secrets: inherit

  trailing-newline-check:
    name: Trailing Newline Check
    if: github.event_name == 'pull_request'
    uses: valkyrjaio/.github/.github/workflows/_trailing-newline-check.yml@716065aae4466b95f0f80c9c5a5e2a92de620af6
    permissions:
      pull-requests: write
      contents: read
    secrets: inherit

  phparkitect:
    name: PHPArkitect
    uses: valkyrjaio/ci-phparkitect-php/.github/workflows/_workflow-call.yml@2ec6d1cb187ce2242270c0a3f4572b76de3b8db3
    with:
      php-version: '8.4'
      paths: |
        ci:
          - '.github/ci/phparkitect/**'
          - '.github/workflows/ci.yml'
        files:
          - '.github/ci/phparkitect/**'
          - '.github/workflows/ci.yml'
          - 'bin/valkyrja'
          - 'functions/**/*.php'
          - 'src/**/*.php'
          - 'tests/**/*.php'
          - 'composer.json'
    secrets: inherit

  phpcodesniffer:
    name: PHP Code Sniffer
    uses: valkyrjaio/ci-phpcodesniffer-php/.github/workflows/_workflow-call.yml@71d50ad10a9cc2e9ef6b15f1d299bddff72b0027
    with:
      php-version: '8.4'
      paths: |
        ci:
          - '.github/ci/phpcodesniffer/**'
          - '.github/workflows/ci.yml'
        files:
          - '.github/ci/phpcodesniffer/**'
          - '.github/workflows/ci.yml'
          - 'bin/valkyrja'
          - 'functions/**/*.php'
          - 'src/**/*.php'
          - 'tests/**/*.php'
          - 'composer.json'
    secrets: inherit

  phpcsfixer:
    name: PHP CS Fixer
    uses: valkyrjaio/ci-phpcsfixer-php/.github/workflows/_workflow-call.yml@c787357a29476f7264e5c8a64057bf9d5c1f86f7
    with:
      php-version: '8.4'
      paths: |
        ci:
          - '.github/ci/phpcsfixer/**'
          - '.github/workflows/ci.yml'
        files:
          - '.github/ci/phpcsfixer/**'
          - '.github/workflows/ci.yml'
          - 'bin/valkyrja'
          - 'functions/**/*.php'
          - 'src/**/*.php'
          - 'tests/**/*.php'
          - 'composer.json'
    secrets: inherit

  phpstan:
    name: PHPStan
    uses: valkyrjaio/ci-phpstan-php/.github/workflows/_workflow-call.yml@766dcf38e0d178e198c5dcbb1ec6bc55f4732599
    with:
      php-version: '8.4'
      additional-directory: '.github/ci/root-and-suggested'
      extensions: 'openswoole'
      composer-options: '--ignore-platform-req=ext-openswoole'
      paths: |
        ci:
          - '.github/ci/phpstan/**'
          - '.github/ci/root-and-suggested/**'
          - '.github/workflows/ci.yml'
        files:
          - '.github/ci/phpstan/**'
          - '.github/ci/root-and-suggested/**'
          - '.github/workflows/ci.yml'
          - 'bin/valkyrja'
          - 'functions/**/*.php'
          - 'src/**/*.php'
          - 'tests/**/*.php'
          - 'composer.json'
    secrets: inherit

  phpunit:
    name: PHPUnit
    uses: valkyrjaio/ci-phpunit-php/.github/workflows/_workflow-call.yml@ca27f8c28932012e8ec6e25c9c949bc410e68b02
    with:
      php-versions: '["8.4", "8.5", "8.6"]'
      php-version-bleeding-edge: '8.6'
      additional-directory: '.github/ci/root-and-suggested'
      extensions: 'mbstring, intl, sodium, fileinfo, pdo, php-mysql, php-sqlite3, php-pgsql, pdo_sqlite, pdo_pgsql, pdo_mysql, openswoole, xdebug'
      composer-options: '--ignore-platform-req=ext-openswoole'
      paths: |
        ci:
          - '.github/ci/phpunit/**'
          - '.github/ci/root-and-suggested/**'
          - '.github/workflows/ci.yml'
        files:
          - '.github/ci/phpunit/**'
          - '.github/ci/root-and-suggested/**'
          - '.github/workflows/ci.yml'
          - 'bin/valkyrja'
          - 'functions/**/*.php'
          - 'src/**/*.php'
          - 'tests/**/*.php'
          - 'composer.json'
    secrets: inherit

  psalm:
    name: Psalm
    uses: valkyrjaio/ci-psalm-php/.github/workflows/_workflow-call.yml@1f216925b5ff78a88c1728d734cab165071b11c2
    with:
      php-version: '8.4'
      additional-directory: '.github/ci/root-and-suggested'
      extensions: 'openswoole'
      composer-options: '--ignore-platform-req=ext-openswoole'
      run-script: 'psalm-shepherd-with-stats'
      paths: |
        ci:
          - '.github/ci/psalm/**'
          - '.github/ci/root-and-suggested/**'
          - '.github/workflows/ci.yml'
        files:
          - '.github/ci/psalm/**'
          - '.github/ci/root-and-suggested/**'
          - '.github/workflows/ci.yml'
          - 'bin/valkyrja'
          - 'functions/**/*.php'
          - 'src/**/*.php'
          - 'tests/**/*.php'
          - 'composer.json'
    secrets: inherit

  rector:
    name: Rector
    uses: valkyrjaio/ci-rector-php/.github/workflows/_workflow-call.yml@0dafdcf499d607c2471faef2a2c3ca06507cb97e
    with:
      php-version: '8.4'
      paths: |
        ci:
          - '.github/ci/rector/**'
          - '.github/workflows/ci.yml'
        files:
          - '.github/ci/rector/**'
          - '.github/workflows/ci.yml'
          - 'bin/valkyrja'
          - 'functions/**/*.php'
          - 'src/**/*.php'
          - 'tests/**/*.php'
          - 'composer.json'
    secrets: inherit
