name: CI

on:
  push:
    branches: [ 'master', '*.x' ]
  pull_request:
    branches: [ 'master', '*.x' ]

permissions:
  pull-requests: write
  contents: read

jobs:
  commit-message-check:
    name: Commit Message Check
    if: github.event_name == 'pull_request'
    uses: valkyrjaio/.github/.github/workflows/_commit-message-check.yml@9b108a21f1a7161aef43c83046266f2c8de60165
    secrets: inherit

  trailing-newline-check:
    name: Trailing Newline Check
    if: github.event_name == 'pull_request'
    uses: valkyrjaio/.github/.github/workflows/_trailing-newline-check.yml@9b108a21f1a7161aef43c83046266f2c8de60165
    permissions:
      pull-requests: write
      contents: read
    secrets: inherit

  phparkitect:
    name: PHPArkitect
    uses: valkyrjaio/ci-phparkitect-php/.github/workflows/_workflow-call.yml@7544c1072fbfbc50496993cae3b78ed3f8faf268
    with:
      php-version: '8.4'
      paths: |
        ci:
          - '.github/ci/phparkitect/**'
          - '.github/workflows/ci.yml'
        files:
          - '.github/ci/phparkitect/**'
          - '.github/workflows/ci.yml'
          - 'bin/valkyrja'
          - 'functions/**/*.php'
          - 'src/**/*.php'
          - 'tests/**/*.php'
          - 'composer.json'
    secrets: inherit

  phpcodesniffer:
    name: PHP Code Sniffer
    uses: valkyrjaio/ci-phpcodesniffer-php/.github/workflows/_workflow-call.yml@09a173a12239c41b2d78f55ebbedf4767ebba5cd
    with:
      php-version: '8.4'
      paths: |
        ci:
          - '.github/ci/phpcodesniffer/**'
          - '.github/workflows/ci.yml'
        files:
          - '.github/ci/phpcodesniffer/**'
          - '.github/workflows/ci.yml'
          - 'bin/valkyrja'
          - 'functions/**/*.php'
          - 'src/**/*.php'
          - 'tests/**/*.php'
          - 'composer.json'
    secrets: inherit

  phpcsfixer:
    name: PHP CS Fixer
    uses: valkyrjaio/ci-phpcsfixer-php/.github/workflows/_workflow-call.yml@97141d7fefe068c14e393e9f85ffd03c1c3e6125
    with:
      php-version: '8.4'
      paths: |
        ci:
          - '.github/ci/phpcsfixer/**'
          - '.github/workflows/ci.yml'
        files:
          - '.github/ci/phpcsfixer/**'
          - '.github/workflows/ci.yml'
          - 'bin/valkyrja'
          - 'functions/**/*.php'
          - 'src/**/*.php'
          - 'tests/**/*.php'
          - 'composer.json'
    secrets: inherit

  phpstan:
    name: PHPStan
    uses: valkyrjaio/ci-phpstan-php/.github/workflows/_workflow-call.yml@cb3703553ad58e3da9a74c14a749ee7c6a3536c5
    with:
      php-version: '8.4'
      additional-directory: '.github/ci/root-and-suggested'
      paths: |
        ci:
          - '.github/ci/phpstan/**'
          - '.github/ci/root-and-suggested/**'
          - '.github/workflows/ci.yml'
        files:
          - '.github/ci/phpstan/**'
          - '.github/ci/root-and-suggested/**'
          - '.github/workflows/ci.yml'
          - 'bin/valkyrja'
          - 'functions/**/*.php'
          - 'src/**/*.php'
          - 'tests/**/*.php'
          - 'composer.json'
    secrets: inherit

  phpunit:
    name: PHPUnit
    uses: valkyrjaio/ci-phpunit-php/.github/workflows/_workflow-call.yml@31ceecef3647bb9e4fe941a9a04c1074ea7e0ecf
    with:
      php-versions: '["8.4", "8.5", "8.6"]'
      php-version-bleeding-edge: '8.6'
      additional-directory: '.github/ci/root-and-suggested'
      extensions: 'mbstring, intl, sodium, fileinfo, pdo, php-mysql, php-sqlite3, php-pgsql, pdo_sqlite, pdo_pgsql, pdo_mysql xdebug'
      paths: |
        ci:
          - '.github/ci/phpunit/**'
          - '.github/ci/root-and-suggested/**'
          - '.github/workflows/ci.yml'
        files:
          - '.github/ci/phpunit/**'
          - '.github/ci/root-and-suggested/**'
          - '.github/workflows/ci.yml'
          - 'bin/valkyrja'
          - 'functions/**/*.php'
          - 'src/**/*.php'
          - 'tests/**/*.php'
          - 'composer.json'
    secrets: inherit

  psalm:
    name: Psalm
    uses: valkyrjaio/ci-psalm-php/.github/workflows/_workflow-call.yml@1f216925b5ff78a88c1728d734cab165071b11c2
    with:
      php-version: '8.4'
      additional-directory: '.github/ci/root-and-suggested'
      run-script: 'psalm-shepherd-with-stats'
      paths: |
        ci:
          - '.github/ci/psalm/**'
          - '.github/ci/root-and-suggested/**'
          - '.github/workflows/ci.yml'
        files:
          - '.github/ci/psalm/**'
          - '.github/ci/root-and-suggested/**'
          - '.github/workflows/ci.yml'
          - 'bin/valkyrja'
          - 'functions/**/*.php'
          - 'src/**/*.php'
          - 'tests/**/*.php'
          - 'composer.json'
    secrets: inherit

  rector:
    name: Rector
    uses: valkyrjaio/ci-rector-php/.github/workflows/_workflow-call.yml@128a1e2050eac14c95f4da0d610eaee9dcdb0583
    with:
      php-version: '8.4'
      paths: |
        ci:
          - '.github/ci/rector/**'
          - '.github/workflows/ci.yml'
        files:
          - '.github/ci/rector/**'
          - '.github/workflows/ci.yml'
          - 'bin/valkyrja'
          - 'functions/**/*.php'
          - 'src/**/*.php'
          - 'tests/**/*.php'
          - 'composer.json'
    secrets: inherit
