name: Commit Message Check

on:
  pull_request:
    branches: [ 'master', '*.x' ]

jobs:
  commit-message-check:
    name: Commit Message Check
    uses: valkyrjaio/.github/.github/workflows/_commit-message-check.yml@master
    permissions:
      pull-requests: write
      contents: read
    secrets: inherit
