name: Create Yearly Release Version Branch

on: workflow_dispatch

run-name: Create new version for upcoming yearly release

jobs:
  create:
    uses: valkyrjaio/.github/.github/workflows/_php-create-version-branch.yml@c56ebc8606ffb9031fd45aec671f7ad5324e86db
    secrets:
      VALKYRJA_GHA_APP_ID: ${{ secrets.VALKYRJA_GHA_APP_ID }}
      VALKYRJA_GHA_PRIVATE_KEY: ${{ secrets.VALKYRJA_GHA_PRIVATE_KEY }}
    with:
      dependencies: |
        [
          {"name": "Root and Suggested Packages", "command": "root-and-suggested-outdated-check-major-release"},
          {"name": "PHPArkitect",                 "command": "phparkitect-outdated-check-major-release"},
          {"name": "PHP Code Sniffer",            "command": "phpcodesniffer-outdated-check-major-release"},
          {"name": "PHP CS Fixer",                "command": "phpcsfixer-outdated-check-major-release"},
          {"name": "PHPStan",                     "command": "phpstan-outdated-check-major-release"},
          {"name": "PHPUnit",                     "command": "phpunit-outdated-check-major-release"},
          {"name": "Psalm",                       "command": "psalm-outdated-check-major-release"},
          {"name": "Rector",                      "command": "rector-outdated-check-major-release"}
        ]
