name: PHPArkitect

on:
  push:
    branches: [ 'master', '*.x' ]
  pull_request:
    branches: [ 'master', '*.x' ]

jobs:
  phparkitect:
    name: PHPArkitect
    uses: valkyrjaio/phparkitect/.github/workflows/_workflow-call.yml@master
    permissions:
      pull-requests: write
      contents: read
    with:
      php-version: '8.4'
      paths: |
        ci:
          - '.github/ci/phparkitect/**'
          - '.github/workflows/phparkitect.yml'
        files:
          - '.github/ci/phparkitect/**'
          - '.github/workflows/phparkitect.yml'
          - 'bin/valkyrja'
          - 'functions/**/*.php'
          - 'src/**/*.php'
          - 'tests/**/*.php'
          - 'composer.json'
