name: PHP CS Fixer

on:
  push:
    branches: [ 'master', '*.x' ]
  pull_request:
    branches: [ 'master', '*.x' ]

jobs:
  phpcsfixer:
    name: PHP CS Fixer
    uses: valkyrjaio/phpcsfixer/.github/workflows/_workflow-call.yml@master
    permissions:
      pull-requests: write
      contents: read
    with:
      php-version: '8.4'
      paths: |
        ci:
          - '.github/ci/phpcsfixer/**'
          - '.github/workflows/phpcsfixer.yml'
        files:
          - '.github/ci/phpcsfixer/**'
          - '.github/workflows/phpcsfixer.yml'
          - 'bin/valkyrja'
          - 'functions/**/*.php'
          - 'src/**/*.php'
          - 'tests/**/*.php'
          - 'composer.json'
