name: PHP Code Sniffer

on:
  push:
    branches: [ 'master', '*.x' ]
  pull_request:
    branches: [ 'master', '*.x' ]

jobs:
  phpcodesniffer:
    name: PHP Code Sniffer
    uses: valkyrjaio/phpcodesniffer/.github/workflows/_workflow-call.yml@master
    permissions:
      pull-requests: write
      contents: read
    with:
      php-version: '8.4'
      paths: |
        ci:
          - '.github/ci/phpcodesniffer/**'
          - '.github/workflows/phpcodesniffer.yml'
        files:
          - '.github/ci/phpcodesniffer/**'
          - '.github/workflows/phpcodesniffer.yml'
          - 'bin/valkyrja'
          - 'functions/**/*.php'
          - 'src/**/*.php'
          - 'tests/**/*.php'
          - 'composer.json'
    secrets: inherit
