name: PHPStan

on:
  push:
    branches: [ 'master', '*.x' ]
  pull_request:
    branches: [ 'master', '*.x' ]

jobs:
  phpstan:
    name: PHPStan
    uses: valkyrjaio/phpstan/.github/workflows/_workflow-call.yml@master
    permissions:
      pull-requests: write
      contents: read
    with:
      php-version: '8.4'
      additional-directory: '.github/ci/root-and-suggested'
      paths: |
        ci:
          - '.github/ci/phpstan/**'
          - '.github/ci/root-and-suggested/**'
          - '.github/workflows/phpstan.yml'
        files:
          - '.github/ci/phpstan/**'
          - '.github/ci/root-and-suggested/**'
          - '.github/workflows/phpstan.yml'
          - 'bin/valkyrja'
          - 'functions/**/*.php'
          - 'src/**/*.php'
          - 'tests/**/*.php'
          - 'composer.json'
    secrets: inherit
