name: PHPUnit

on:
  push:
    branches: [ 'master', '*.x' ]
  pull_request:
    branches: [ 'master', '*.x' ]

jobs:
  phpunit:
    name: PHPUnit
    uses: valkyrjaio/phpunit/.github/workflows/_workflow-call.yml@master
    permissions:
      pull-requests: write
      contents: read
    with:
      php-versions: '["8.4", "8.5", "8.6"]'
      php-version-bleeding-edge: '8.6'
      additional-directory: '.github/ci/root-and-suggested'
      extensions: 'mbstring, intl, sodium, fileinfo, pdo, php-mysql, php-sqlite3, php-pgsql, pdo_sqlite, pdo_pgsql, pdo_mysql xdebug'
      paths: |
        ci:
          - '.github/ci/phpunit/**'
          - '.github/ci/root-and-suggested/**'
          - '.github/workflows/phpunit.yml'
        files:
          - '.github/ci/phpunit/**'
          - '.github/ci/root-and-suggested/**'
          - '.github/workflows/phpunit.yml'
          - 'bin/valkyrja'
          - 'functions/**/*.php'
          - 'src/**/*.php'
          - 'tests/**/*.php'
          - 'composer.json'
