name: Rebase from Master

on:
  workflow_dispatch:

run-name: "Rebase ${{ github.ref_name }} from master"

jobs:
  rebase:
    uses: valkyrjaio/.github/.github/workflows/_rebase-from-master.yml@f0560559020d79edb410ef75387e081d75026e45
    permissions:
      contents: write
    secrets:
      VALKYRJA_GHA_APP_ID: ${{ secrets.VALKYRJA_GHA_APP_ID }}
      VALKYRJA_GHA_PRIVATE_KEY: ${{ secrets.VALKYRJA_GHA_PRIVATE_KEY }}
