name: Rebase to Master

on:
  workflow_dispatch:

run-name: "Rebase ${{ github.ref_name }} to master"

jobs:
  rebase:
    uses: valkyrjaio/.github/.github/workflows/_rebase-to-master.yml@716065aae4466b95f0f80c9c5a5e2a92de620af6
    permissions:
      contents: write
    secrets: inherit
