name: Rebase to Master

on:
  workflow_dispatch:

run-name: "Rebase ${{ github.ref_name }} to master"

jobs:
  rebase:
    uses: valkyrjaio/.github/.github/workflows/_rebase-to-master.yml@2e33f6236ca98885ec892f81ebb8e38aef29c8f4
    permissions:
      contents: write
    secrets: inherit