name: Rebase from Master

on:
  workflow_dispatch:

run-name: "Rebase ${{ github.ref_name }} from master"

jobs:
  rebase:
    uses: valkyrjaio/.github/.github/workflows/_rebase-from-master.yml@a15724723b7c6668fb26b8c3bec90ddedea44dcb
    permissions:
      contents: write
    secrets: inherit
