name: Create a New Release

on:
  workflow_dispatch:
    inputs:
      bump:
        description: 'Version component to bump (auto, patch, feature, yearly, or rc)'
        required: true
        type: choice
        default: auto
        options:
          - auto
          - patch
          - feature
          - yearly
          - rc

run-name: "Release ${{ inputs.bump }} bump on ${{ github.ref_name }}"

permissions:
  contents: write

jobs:
  release:
    uses: valkyrjaio/.github/.github/workflows/_php-create-release.yml@f0560559020d79edb410ef75387e081d75026e45
    secrets:
      VALKYRJA_GHA_APP_ID: ${{ secrets.VALKYRJA_GHA_APP_ID }}
      VALKYRJA_GHA_PRIVATE_KEY: ${{ secrets.VALKYRJA_GHA_PRIVATE_KEY }}
    with:
      bump: ${{ inputs.bump }}
      dependencies: |
        [
          {"name": "Root and Suggested Packages", "command": "root-and-suggested-outdated-check"},
          {"name": "PHPArkitect",                 "command": "phparkitect-outdated-check"},
          {"name": "PHP Code Sniffer",            "command": "phpcodesniffer-outdated-check"},
          {"name": "PHP CS Fixer",                "command": "phpcsfixer-outdated-check"},
          {"name": "PHPStan",                     "command": "phpstan-outdated-check"},
          {"name": "PHPUnit",                     "command": "phpunit-outdated-check"},
          {"name": "Psalm",                       "command": "psalm-outdated-check"},
          {"name": "Rector",                      "command": "rector-outdated-check"}
        ]
      info-class-path: src/Valkyrja/Application/Constant/ApplicationInfo.php
      info-class-name: ApplicationInfo
