name: Create a New Release

on:
  workflow_dispatch:
    inputs:
      bump:
        description: 'Version component to bump'
        required: true
        type: choice
        options:
          - patch
          - minor
          - major
          - rc

run-name: "Release ${{ inputs.bump }} bump on ${{ github.ref_name }}"

permissions:
  contents: write

jobs:
  release:
    uses: valkyrjaio/.github/.github/workflows/_create-php-release.yml@2bbc24ee6f121652e6be7a6a9a7a32a376f9a817
    secrets: inherit
    with:
      bump: ${{ inputs.bump }}
      dependencies: |
        [
          {"name": "Root and Suggested Packages", "command": "root-and-suggested-outdated-check"},
          {"name": "PHPArkitect",                 "command": "phparkitect-outdated-check"},
          {"name": "PHP Code Sniffer",            "command": "phpcodesniffer-outdated-check"},
          {"name": "PHP CS Fixer",                "command": "phpcsfixer-outdated-check"},
          {"name": "PHPStan",                     "command": "phpstan-outdated-check"},
          {"name": "PHPUnit",                     "command": "phpunit-outdated-check"},
          {"name": "Psalm",                       "command": "psalm-outdated-check"},
          {"name": "Rector",                      "command": "rector-outdated-check"}
        ]
      info-class-path: src/Valkyrja/Application/Constant/ApplicationInfo.php
      info-class-name: ApplicationInfo