name: Restore Branch From Backup

on:
  workflow_dispatch:

run-name: "Restore ${{ github.ref_name }} from ${{ github.ref_name }}-backup"

jobs:
  restore:
    uses: valkyrjaio/.github/.github/workflows/_restore-branch-from-backup.yml@a377bb5bc151aa160a65143b688f383fd085455f
    permissions:
      contents: write
    secrets: inherit
