name: Restore Branch From Backup

on:
  workflow_dispatch:

run-name: "Restore ${{ github.ref_name }} from ${{ github.ref_name }}-backup"

jobs:
  restore:
    uses: valkyrjaio/.github/.github/workflows/_restore-branch-from-backup.yml@80d66c1e2b574520c47a2e585a7ec433b9c587b2
    permissions:
      contents: write
    secrets:
      VALKYRJA_GHA_APP_ID: ${{ secrets.VALKYRJA_GHA_APP_ID }}
      VALKYRJA_GHA_PRIVATE_KEY: ${{ secrets.VALKYRJA_GHA_PRIVATE_KEY }}
